// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topos/points/v1/points.proto

package points

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Brand struct {
	// The name of the point brand. It must have the format `"brands/{brand}"`.
	// `{brand}` must match the [regular
	// expression](https://github.com/google/re2/wiki/Syntax)
	// `^[a-z\d]+(-[a-z\d]+)*$`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The display name of the brand.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The formatted, single-line address of the brand's headquarters.
	FormattedAddress string `protobuf:"bytes,3,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	// The email of the brand.
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// The realestate email of the brand.
	RealestateEmail string `protobuf:"bytes,5,opt,name=realestate_email,json=realestateEmail,proto3" json:"realestate_email,omitempty"`
	// The phone number of the brand.
	PhoneNumber string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// The contacts for the brand.
	Contacts []*Brand_Contact `protobuf:"bytes,7,rep,name=contacts,proto3" json:"contacts,omitempty"`
	// The [2017 NAICS
	// code](https://www.census.gov/cgi-bin/sssd/naics/naicsrch?chart=2017) of
	// the brand.
	Naics string `protobuf:"bytes,8,opt,name=naics,proto3" json:"naics,omitempty"`
	// The prefered square footage of the brand.
	PreferredGla string `protobuf:"bytes,9,opt,name=preferred_gla,json=preferredGla,proto3" json:"preferred_gla,omitempty"`
	// The postal code of the brand's headquarters.
	PostalCode string `protobuf:"bytes,10,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// The creation timestamp of the brand.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of an brand.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Brand) Reset()         { *m = Brand{} }
func (m *Brand) String() string { return proto.CompactTextString(m) }
func (*Brand) ProtoMessage()    {}
func (*Brand) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{0}
}

func (m *Brand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand.Unmarshal(m, b)
}
func (m *Brand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand.Marshal(b, m, deterministic)
}
func (m *Brand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand.Merge(m, src)
}
func (m *Brand) XXX_Size() int {
	return xxx_messageInfo_Brand.Size(m)
}
func (m *Brand) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand.DiscardUnknown(m)
}

var xxx_messageInfo_Brand proto.InternalMessageInfo

func (m *Brand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Brand) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Brand) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Brand) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Brand) GetRealestateEmail() string {
	if m != nil {
		return m.RealestateEmail
	}
	return ""
}

func (m *Brand) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Brand) GetContacts() []*Brand_Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Brand) GetNaics() string {
	if m != nil {
		return m.Naics
	}
	return ""
}

func (m *Brand) GetPreferredGla() string {
	if m != nil {
		return m.PreferredGla
	}
	return ""
}

func (m *Brand) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Brand) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Brand) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Brand_Contact struct {
	// The full name of the contact.
	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// The title of the contact.
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand_Contact) Reset()         { *m = Brand_Contact{} }
func (m *Brand_Contact) String() string { return proto.CompactTextString(m) }
func (*Brand_Contact) ProtoMessage()    {}
func (*Brand_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{0, 0}
}

func (m *Brand_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand_Contact.Unmarshal(m, b)
}
func (m *Brand_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand_Contact.Marshal(b, m, deterministic)
}
func (m *Brand_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand_Contact.Merge(m, src)
}
func (m *Brand_Contact) XXX_Size() int {
	return xxx_messageInfo_Brand_Contact.Size(m)
}
func (m *Brand_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Brand_Contact proto.InternalMessageInfo

func (m *Brand_Contact) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Brand_Contact) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type LatLng struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLng) Reset()         { *m = LatLng{} }
func (m *LatLng) String() string { return proto.CompactTextString(m) }
func (*LatLng) ProtoMessage()    {}
func (*LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{1}
}

func (m *LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLng.Unmarshal(m, b)
}
func (m *LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLng.Marshal(b, m, deterministic)
}
func (m *LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLng.Merge(m, src)
}
func (m *LatLng) XXX_Size() int {
	return xxx_messageInfo_LatLng.Size(m)
}
func (m *LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_LatLng proto.InternalMessageInfo

func (m *LatLng) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LatLng) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Point struct {
	// The name of the point. It must have the format `"points/{point}"`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The name of the point's brand if it has one. It must have the format
	// `"brands/{brand}"`. `{brand}` must match the [regular
	// expression](https://github.com/google/re2/wiki/Syntax)
	// `^[a-z\d]+(-[a-z\d]+)*$`
	Brand string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	// The display name of the point.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The formatted, single-line address.
	FormattedAddress string `protobuf:"bytes,4,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	// The geocoded point address.
	Location *LatLng `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// A list of point tags.
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// The creation timestamp of the point.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of an point.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{2}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Point) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Point) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Point) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Point) GetLocation() *LatLng {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Point) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Point) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Point) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Tag struct {
	// The name of the tag. It must have the format `"tags/{tag}"`. `{tag}`
	// must match the [regular
	// expression](https://github.com/google/re2/wiki/Syntax)
	// `^[a-z\d]+(-[a-z\d]+)*$`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The display name of the tag.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Exclude tag from results.
	Exclude bool `protobuf:"varint,3,opt,name=exclude,proto3" json:"exclude,omitempty"`
	// The creation timestamp of the tag.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of the tag.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{3}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Tag) GetExclude() bool {
	if m != nil {
		return m.Exclude
	}
	return false
}

func (m *Tag) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Tag) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type PointSource struct {
	// The name of the point source. It must have the format
	// `"sources/{source}/pointSources/{point_source}"`. `{source}` must match
	// the [regular expression](https://github.com/google/re2/wiki/Syntax)
	// `^[a-z\d]+(-[a-z\d]+)*$`. {point_source} is the remote point source ID.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The name of the point associated with this point source if there is one.
	// It must have the format `"points/{point}"`.
	Point string `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	// The display name of the point source.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The formatted, single-line address.
	FormattedAddress string `protobuf:"bytes,4,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	// The source-geocoded address.
	Location *LatLng `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// A list of potentially unnormalized, source-provided tags.
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// The creation timestamp of the point source.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of an point source.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PointSource) Reset()         { *m = PointSource{} }
func (m *PointSource) String() string { return proto.CompactTextString(m) }
func (*PointSource) ProtoMessage()    {}
func (*PointSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{4}
}

func (m *PointSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointSource.Unmarshal(m, b)
}
func (m *PointSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointSource.Marshal(b, m, deterministic)
}
func (m *PointSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointSource.Merge(m, src)
}
func (m *PointSource) XXX_Size() int {
	return xxx_messageInfo_PointSource.Size(m)
}
func (m *PointSource) XXX_DiscardUnknown() {
	xxx_messageInfo_PointSource.DiscardUnknown(m)
}

var xxx_messageInfo_PointSource proto.InternalMessageInfo

func (m *PointSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PointSource) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

func (m *PointSource) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *PointSource) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *PointSource) GetLocation() *LatLng {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *PointSource) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PointSource) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *PointSource) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type GetBrandRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandRequest) Reset()         { *m = GetBrandRequest{} }
func (m *GetBrandRequest) String() string { return proto.CompactTextString(m) }
func (*GetBrandRequest) ProtoMessage()    {}
func (*GetBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{5}
}

func (m *GetBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandRequest.Unmarshal(m, b)
}
func (m *GetBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandRequest.Marshal(b, m, deterministic)
}
func (m *GetBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandRequest.Merge(m, src)
}
func (m *GetBrandRequest) XXX_Size() int {
	return xxx_messageInfo_GetBrandRequest.Size(m)
}
func (m *GetBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandRequest proto.InternalMessageInfo

func (m *GetBrandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetBrandRequest struct {
	Brand                *Brand   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBrandRequest) Reset()         { *m = SetBrandRequest{} }
func (m *SetBrandRequest) String() string { return proto.CompactTextString(m) }
func (*SetBrandRequest) ProtoMessage()    {}
func (*SetBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{6}
}

func (m *SetBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBrandRequest.Unmarshal(m, b)
}
func (m *SetBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBrandRequest.Marshal(b, m, deterministic)
}
func (m *SetBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBrandRequest.Merge(m, src)
}
func (m *SetBrandRequest) XXX_Size() int {
	return xxx_messageInfo_SetBrandRequest.Size(m)
}
func (m *SetBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBrandRequest proto.InternalMessageInfo

func (m *SetBrandRequest) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

type DeleteBrandRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBrandRequest) Reset()         { *m = DeleteBrandRequest{} }
func (m *DeleteBrandRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBrandRequest) ProtoMessage()    {}
func (*DeleteBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{7}
}

func (m *DeleteBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBrandRequest.Unmarshal(m, b)
}
func (m *DeleteBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBrandRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBrandRequest.Merge(m, src)
}
func (m *DeleteBrandRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBrandRequest.Size(m)
}
func (m *DeleteBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBrandRequest proto.InternalMessageInfo

func (m *DeleteBrandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPointRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointRequest) Reset()         { *m = GetPointRequest{} }
func (m *GetPointRequest) String() string { return proto.CompactTextString(m) }
func (*GetPointRequest) ProtoMessage()    {}
func (*GetPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{8}
}

func (m *GetPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointRequest.Unmarshal(m, b)
}
func (m *GetPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointRequest.Marshal(b, m, deterministic)
}
func (m *GetPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointRequest.Merge(m, src)
}
func (m *GetPointRequest) XXX_Size() int {
	return xxx_messageInfo_GetPointRequest.Size(m)
}
func (m *GetPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointRequest proto.InternalMessageInfo

func (m *GetPointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdatePointRequest struct {
	Point                *Point   `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePointRequest) Reset()         { *m = UpdatePointRequest{} }
func (m *UpdatePointRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePointRequest) ProtoMessage()    {}
func (*UpdatePointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{9}
}

func (m *UpdatePointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePointRequest.Unmarshal(m, b)
}
func (m *UpdatePointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePointRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePointRequest.Merge(m, src)
}
func (m *UpdatePointRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePointRequest.Size(m)
}
func (m *UpdatePointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePointRequest proto.InternalMessageInfo

func (m *UpdatePointRequest) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

type DeletePointRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePointRequest) Reset()         { *m = DeletePointRequest{} }
func (m *DeletePointRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePointRequest) ProtoMessage()    {}
func (*DeletePointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{10}
}

func (m *DeletePointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePointRequest.Unmarshal(m, b)
}
func (m *DeletePointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePointRequest.Marshal(b, m, deterministic)
}
func (m *DeletePointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePointRequest.Merge(m, src)
}
func (m *DeletePointRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePointRequest.Size(m)
}
func (m *DeletePointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePointRequest proto.InternalMessageInfo

func (m *DeletePointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTagRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagRequest) Reset()         { *m = GetTagRequest{} }
func (m *GetTagRequest) String() string { return proto.CompactTextString(m) }
func (*GetTagRequest) ProtoMessage()    {}
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{11}
}

func (m *GetTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagRequest.Unmarshal(m, b)
}
func (m *GetTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagRequest.Marshal(b, m, deterministic)
}
func (m *GetTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagRequest.Merge(m, src)
}
func (m *GetTagRequest) XXX_Size() int {
	return xxx_messageInfo_GetTagRequest.Size(m)
}
func (m *GetTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagRequest proto.InternalMessageInfo

func (m *GetTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetTagRequest struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTagRequest) Reset()         { *m = SetTagRequest{} }
func (m *SetTagRequest) String() string { return proto.CompactTextString(m) }
func (*SetTagRequest) ProtoMessage()    {}
func (*SetTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{12}
}

func (m *SetTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTagRequest.Unmarshal(m, b)
}
func (m *SetTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTagRequest.Marshal(b, m, deterministic)
}
func (m *SetTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTagRequest.Merge(m, src)
}
func (m *SetTagRequest) XXX_Size() int {
	return xxx_messageInfo_SetTagRequest.Size(m)
}
func (m *SetTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTagRequest proto.InternalMessageInfo

func (m *SetTagRequest) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type DeleteTagRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagRequest) Reset()         { *m = DeleteTagRequest{} }
func (m *DeleteTagRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagRequest) ProtoMessage()    {}
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{13}
}

func (m *DeleteTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagRequest.Unmarshal(m, b)
}
func (m *DeleteTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagRequest.Merge(m, src)
}
func (m *DeleteTagRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagRequest.Size(m)
}
func (m *DeleteTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagRequest proto.InternalMessageInfo

func (m *DeleteTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPointSourceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointSourceRequest) Reset()         { *m = GetPointSourceRequest{} }
func (m *GetPointSourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetPointSourceRequest) ProtoMessage()    {}
func (*GetPointSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{14}
}

func (m *GetPointSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointSourceRequest.Unmarshal(m, b)
}
func (m *GetPointSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointSourceRequest.Marshal(b, m, deterministic)
}
func (m *GetPointSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointSourceRequest.Merge(m, src)
}
func (m *GetPointSourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetPointSourceRequest.Size(m)
}
func (m *GetPointSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointSourceRequest proto.InternalMessageInfo

func (m *GetPointSourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetPointSourceRequest struct {
	PointSource          *PointSource `protobuf:"bytes,1,opt,name=point_source,json=pointSource,proto3" json:"point_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetPointSourceRequest) Reset()         { *m = SetPointSourceRequest{} }
func (m *SetPointSourceRequest) String() string { return proto.CompactTextString(m) }
func (*SetPointSourceRequest) ProtoMessage()    {}
func (*SetPointSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{15}
}

func (m *SetPointSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPointSourceRequest.Unmarshal(m, b)
}
func (m *SetPointSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPointSourceRequest.Marshal(b, m, deterministic)
}
func (m *SetPointSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPointSourceRequest.Merge(m, src)
}
func (m *SetPointSourceRequest) XXX_Size() int {
	return xxx_messageInfo_SetPointSourceRequest.Size(m)
}
func (m *SetPointSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPointSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPointSourceRequest proto.InternalMessageInfo

func (m *SetPointSourceRequest) GetPointSource() *PointSource {
	if m != nil {
		return m.PointSource
	}
	return nil
}

type DeletePointSourceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePointSourceRequest) Reset()         { *m = DeletePointSourceRequest{} }
func (m *DeletePointSourceRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePointSourceRequest) ProtoMessage()    {}
func (*DeletePointSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{16}
}

func (m *DeletePointSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePointSourceRequest.Unmarshal(m, b)
}
func (m *DeletePointSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePointSourceRequest.Marshal(b, m, deterministic)
}
func (m *DeletePointSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePointSourceRequest.Merge(m, src)
}
func (m *DeletePointSourceRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePointSourceRequest.Size(m)
}
func (m *DeletePointSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePointSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePointSourceRequest proto.InternalMessageInfo

func (m *DeletePointSourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LinkPointSourceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PointSource          string   `protobuf:"bytes,2,opt,name=point_source,json=pointSource,proto3" json:"point_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkPointSourceRequest) Reset()         { *m = LinkPointSourceRequest{} }
func (m *LinkPointSourceRequest) String() string { return proto.CompactTextString(m) }
func (*LinkPointSourceRequest) ProtoMessage()    {}
func (*LinkPointSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{17}
}

func (m *LinkPointSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkPointSourceRequest.Unmarshal(m, b)
}
func (m *LinkPointSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkPointSourceRequest.Marshal(b, m, deterministic)
}
func (m *LinkPointSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkPointSourceRequest.Merge(m, src)
}
func (m *LinkPointSourceRequest) XXX_Size() int {
	return xxx_messageInfo_LinkPointSourceRequest.Size(m)
}
func (m *LinkPointSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkPointSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkPointSourceRequest proto.InternalMessageInfo

func (m *LinkPointSourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LinkPointSourceRequest) GetPointSource() string {
	if m != nil {
		return m.PointSource
	}
	return ""
}

type LinkPointSourceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkPointSourceResponse) Reset()         { *m = LinkPointSourceResponse{} }
func (m *LinkPointSourceResponse) String() string { return proto.CompactTextString(m) }
func (*LinkPointSourceResponse) ProtoMessage()    {}
func (*LinkPointSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bd33bd76af5b35, []int{18}
}

func (m *LinkPointSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkPointSourceResponse.Unmarshal(m, b)
}
func (m *LinkPointSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkPointSourceResponse.Marshal(b, m, deterministic)
}
func (m *LinkPointSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkPointSourceResponse.Merge(m, src)
}
func (m *LinkPointSourceResponse) XXX_Size() int {
	return xxx_messageInfo_LinkPointSourceResponse.Size(m)
}
func (m *LinkPointSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkPointSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkPointSourceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Brand)(nil), "topos.points.v1.Brand")
	proto.RegisterType((*Brand_Contact)(nil), "topos.points.v1.Brand.Contact")
	proto.RegisterType((*LatLng)(nil), "topos.points.v1.LatLng")
	proto.RegisterType((*Point)(nil), "topos.points.v1.Point")
	proto.RegisterType((*Tag)(nil), "topos.points.v1.Tag")
	proto.RegisterType((*PointSource)(nil), "topos.points.v1.PointSource")
	proto.RegisterType((*GetBrandRequest)(nil), "topos.points.v1.GetBrandRequest")
	proto.RegisterType((*SetBrandRequest)(nil), "topos.points.v1.SetBrandRequest")
	proto.RegisterType((*DeleteBrandRequest)(nil), "topos.points.v1.DeleteBrandRequest")
	proto.RegisterType((*GetPointRequest)(nil), "topos.points.v1.GetPointRequest")
	proto.RegisterType((*UpdatePointRequest)(nil), "topos.points.v1.UpdatePointRequest")
	proto.RegisterType((*DeletePointRequest)(nil), "topos.points.v1.DeletePointRequest")
	proto.RegisterType((*GetTagRequest)(nil), "topos.points.v1.GetTagRequest")
	proto.RegisterType((*SetTagRequest)(nil), "topos.points.v1.SetTagRequest")
	proto.RegisterType((*DeleteTagRequest)(nil), "topos.points.v1.DeleteTagRequest")
	proto.RegisterType((*GetPointSourceRequest)(nil), "topos.points.v1.GetPointSourceRequest")
	proto.RegisterType((*SetPointSourceRequest)(nil), "topos.points.v1.SetPointSourceRequest")
	proto.RegisterType((*DeletePointSourceRequest)(nil), "topos.points.v1.DeletePointSourceRequest")
	proto.RegisterType((*LinkPointSourceRequest)(nil), "topos.points.v1.LinkPointSourceRequest")
	proto.RegisterType((*LinkPointSourceResponse)(nil), "topos.points.v1.LinkPointSourceResponse")
}

func init() { proto.RegisterFile("topos/points/v1/points.proto", fileDescriptor_58bd33bd76af5b35) }

var fileDescriptor_58bd33bd76af5b35 = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x5f, 0x6f, 0xdb, 0x54,
	0x14, 0x57, 0x9a, 0x26, 0x4d, 0x8f, 0xdb, 0xa6, 0xbd, 0x6b, 0x3b, 0xd7, 0x2d, 0x5b, 0xea, 0x6a,
	0x25, 0x4b, 0x8b, 0xa3, 0xb5, 0x48, 0x48, 0x19, 0x68, 0xa2, 0xdb, 0x54, 0x09, 0x55, 0x03, 0xc5,
	0x45, 0x02, 0x5e, 0xa2, 0xdb, 0xf8, 0xd6, 0x58, 0x73, 0x6c, 0x63, 0xdf, 0x4c, 0x4c, 0x68, 0x2f,
	0xf0, 0x11, 0x78, 0xe2, 0x09, 0x89, 0xcf, 0xc2, 0x13, 0x4f, 0x48, 0x7c, 0x05, 0xbe, 0x06, 0x12,
	0xba, 0xe7, 0xda, 0x89, 0x13, 0xdb, 0x49, 0xd8, 0xcb, 0x5e, 0x78, 0xcb, 0x3d, 0xe7, 0xe7, 0x7b,
	0x7e, 0xe7, 0xdf, 0xcf, 0x0e, 0x1c, 0x70, 0x3f, 0xf0, 0xa3, 0x76, 0xe0, 0x3b, 0x1e, 0x8f, 0xda,
	0xaf, 0x1e, 0xc5, 0xbf, 0x8c, 0x20, 0xf4, 0xb9, 0x4f, 0xea, 0xe8, 0x35, 0x62, 0xdb, 0xab, 0x47,
	0xda, 0x81, 0xed, 0xfb, 0xb6, 0xcb, 0xda, 0x34, 0x70, 0xda, 0xd4, 0xf3, 0x7c, 0x4e, 0xb9, 0xe3,
	0x7b, 0x31, 0x5c, 0xdb, 0x8f, 0xbd, 0x78, 0xba, 0x19, 0xde, 0xb6, 0xd9, 0x20, 0xe0, 0xaf, 0x63,
	0xe7, 0xfd, 0x69, 0x27, 0x77, 0x06, 0x2c, 0xe2, 0x74, 0x10, 0x48, 0x80, 0xfe, 0xeb, 0x32, 0x54,
	0x2e, 0x42, 0xea, 0x59, 0x84, 0xc0, 0xb2, 0x47, 0x07, 0x4c, 0x2d, 0x35, 0x4a, 0xcd, 0xd5, 0x2e,
	0xfe, 0x26, 0x87, 0xb0, 0x66, 0x39, 0x51, 0xe0, 0xd2, 0xd7, 0x3d, 0xf4, 0x2d, 0xa1, 0x4f, 0x89,
	0x6d, 0x2f, 0x04, 0xe4, 0x04, 0xb6, 0x6e, 0xfd, 0x70, 0x40, 0x39, 0x67, 0x56, 0x8f, 0x5a, 0x56,
	0xc8, 0xa2, 0x48, 0x2d, 0x23, 0x6e, 0x73, 0xe4, 0xf8, 0x54, 0xda, 0xc9, 0x36, 0x54, 0xd8, 0x80,
	0x3a, 0xae, 0xba, 0x8c, 0x00, 0x79, 0x20, 0x0f, 0x61, 0x33, 0x64, 0xd4, 0x15, 0xbc, 0x38, 0xeb,
	0x49, 0x40, 0x05, 0x01, 0xf5, 0xb1, 0xfd, 0x39, 0x42, 0x0f, 0x61, 0x2d, 0xf8, 0xd6, 0xf7, 0x58,
	0xcf, 0x1b, 0x0e, 0x6e, 0x58, 0xa8, 0x56, 0x25, 0x21, 0xb4, 0xbd, 0x40, 0x13, 0xe9, 0x40, 0xad,
	0xef, 0x7b, 0x9c, 0xf6, 0x79, 0xa4, 0xae, 0x34, 0xca, 0x4d, 0xe5, 0xec, 0x9e, 0x31, 0x55, 0x51,
	0x03, 0x33, 0x36, 0x9e, 0x4a, 0x58, 0x77, 0x84, 0x17, 0xfc, 0x3c, 0xea, 0xf4, 0x23, 0xb5, 0x26,
	0xf9, 0xe1, 0x81, 0x1c, 0xc1, 0x7a, 0x10, 0xb2, 0x5b, 0x16, 0x86, 0xcc, 0xea, 0xd9, 0x2e, 0x55,
	0x57, 0xd1, 0xbb, 0x36, 0x32, 0x5e, 0xba, 0x94, 0xdc, 0x07, 0x25, 0xf0, 0x23, 0x4e, 0xdd, 0x5e,
	0xdf, 0xb7, 0x98, 0x0a, 0x08, 0x01, 0x69, 0x7a, 0xea, 0x5b, 0x8c, 0x3c, 0x06, 0xa5, 0x1f, 0x32,
	0x91, 0xa1, 0xe8, 0x81, 0xba, 0xd1, 0x28, 0x35, 0x95, 0x33, 0xcd, 0x90, 0x0d, 0x32, 0x92, 0x06,
	0x19, 0xd7, 0x49, 0x83, 0xba, 0x20, 0xe1, 0xc2, 0x20, 0x1e, 0x1e, 0x06, 0xd6, 0xe8, 0xe1, 0xfa,
	0xfc, 0x87, 0x25, 0x5c, 0x18, 0xb4, 0x8f, 0x61, 0x25, 0x4e, 0x95, 0xec, 0xc3, 0xea, 0xed, 0xd0,
	0x75, 0x7b, 0xa9, 0x4e, 0xd7, 0x84, 0x01, 0x5b, 0xb9, 0x0d, 0x15, 0xee, 0x70, 0x37, 0x69, 0xb3,
	0x3c, 0xe8, 0x17, 0x50, 0xbd, 0xa2, 0xfc, 0xca, 0xb3, 0x89, 0x06, 0x35, 0x97, 0x72, 0x87, 0x0f,
	0x2d, 0xf9, 0x6c, 0xa9, 0x3b, 0x3a, 0x93, 0x03, 0x58, 0x75, 0x7d, 0xcf, 0x96, 0xce, 0x25, 0x74,
	0x8e, 0x0d, 0xfa, 0xef, 0x4b, 0x50, 0xf9, 0x42, 0x54, 0x3f, 0x77, 0xca, 0xb6, 0xa1, 0x72, 0x23,
	0x1a, 0x92, 0xc4, 0xc5, 0x43, 0x66, 0xf6, 0xca, 0x0b, 0xce, 0xde, 0x72, 0xc1, 0xec, 0x9d, 0x43,
	0xcd, 0xf5, 0xfb, 0xb8, 0x3a, 0x38, 0x5d, 0xca, 0xd9, 0xdd, 0xcc, 0x5c, 0xc8, 0x44, 0xbb, 0x23,
	0xa0, 0xa0, 0xcb, 0xa9, 0x1d, 0xa9, 0xd5, 0x46, 0x59, 0xd0, 0x15, 0xbf, 0xdf, 0x5d, 0x23, 0xf5,
	0x3f, 0x4b, 0x50, 0xbe, 0xa6, 0xf6, 0xdb, 0xae, 0xaa, 0x0a, 0x2b, 0xec, 0xfb, 0xbe, 0x2b, 0x3a,
	0x24, 0x8a, 0x59, 0xeb, 0x26, 0xc7, 0x77, 0x98, 0xd2, 0x1f, 0x4b, 0xa0, 0xe0, 0x64, 0x98, 0xfe,
	0x30, 0xec, 0xb3, 0xa2, 0xf9, 0xc0, 0x16, 0x25, 0xf3, 0x81, 0x87, 0xff, 0xe7, 0x23, 0x5b, 0xcc,
	0x07, 0x50, 0xbf, 0x64, 0x1c, 0xc5, 0xad, 0xcb, 0xbe, 0x1b, 0xb2, 0x28, 0x77, 0xdf, 0xf4, 0x27,
	0x50, 0x37, 0xa7, 0x60, 0xa7, 0xc9, 0x0a, 0x96, 0x30, 0xe0, 0x6e, 0xbe, 0x62, 0xc6, 0xab, 0xa9,
	0x37, 0x81, 0x3c, 0x63, 0x2e, 0xe3, 0x6c, 0x6e, 0x28, 0xc9, 0x08, 0x1b, 0x3c, 0x0b, 0x76, 0x01,
	0xe4, 0x4b, 0x4c, 0x63, 0x02, 0x79, 0x9a, 0xf4, 0xbd, 0x88, 0x94, 0x44, 0x4b, 0xd0, 0x98, 0xd4,
	0xdc, 0x68, 0x47, 0xb0, 0x7e, 0xc9, 0xf8, 0x35, 0xb5, 0x67, 0x81, 0x3e, 0x82, 0x75, 0x73, 0x02,
	0x74, 0x0c, 0x65, 0x4e, 0xed, 0x98, 0xcb, 0x76, 0x86, 0x8b, 0x40, 0x0a, 0x80, 0x7e, 0x0c, 0x9b,
	0x92, 0xc7, 0x9c, 0x00, 0x27, 0xb0, 0x93, 0x94, 0x46, 0xce, 0xfe, 0x2c, 0xf0, 0x57, 0xb0, 0x63,
	0xe6, 0x82, 0x9f, 0xc0, 0x1a, 0x72, 0xe8, 0x45, 0x68, 0x8e, 0xe9, 0x1d, 0xe4, 0x97, 0x2a, 0x7e,
	0x54, 0x09, 0xc6, 0x07, 0xdd, 0x00, 0x35, 0x55, 0xb6, 0xf9, 0x4c, 0x3e, 0x87, 0xdd, 0x2b, 0xc7,
	0x7b, 0xb9, 0x18, 0x1a, 0xdf, 0xd7, 0x69, 0x7a, 0xb1, 0x2a, 0xa5, 0x09, 0xec, 0xc1, 0xdd, 0xcc,
	0x85, 0x51, 0xe0, 0x7b, 0x11, 0x3b, 0xfb, 0x47, 0x81, 0x2a, 0xda, 0x23, 0x42, 0xa1, 0x96, 0x8c,
	0x36, 0x69, 0x64, 0xb2, 0x9b, 0x9a, 0x7a, 0xad, 0x60, 0x7e, 0xf5, 0xfd, 0x1f, 0xff, 0xfa, 0xfb,
	0xe7, 0xa5, 0x1d, 0x72, 0x47, 0x7c, 0x74, 0xfd, 0x20, 0x18, 0x7e, 0x82, 0x13, 0x1d, 0xb5, 0x5b,
	0x6f, 0x48, 0x08, 0x35, 0xb3, 0x38, 0x84, 0xb9, 0x60, 0x88, 0x53, 0x0c, 0x71, 0xac, 0xbf, 0x87,
	0x21, 0xf0, 0x76, 0x63, 0x32, 0x50, 0x27, 0x62, 0xbc, 0x13, 0xbf, 0xe4, 0x6c, 0x50, 0x52, 0x9b,
	0x44, 0x8e, 0x32, 0x97, 0x66, 0xf7, 0x4c, 0xdb, 0xcd, 0xa8, 0xc1, 0x73, 0xf1, 0xc5, 0x97, 0x24,
	0xd7, 0xca, 0x4d, 0x4e, 0xd6, 0x4f, 0xbe, 0x83, 0x73, 0xeb, 0x97, 0xde, 0x1a, 0xad, 0x60, 0xd5,
	0xf2, 0xea, 0x17, 0x7f, 0xc4, 0xb6, 0xde, 0x10, 0x0e, 0x4a, 0x6a, 0x89, 0x73, 0x72, 0xc9, 0xae,
	0x78, 0x61, 0xa0, 0x26, 0x06, 0xd2, 0xb5, 0x3d, 0x0c, 0x84, 0x5e, 0x63, 0x32, 0x5c, 0x27, 0x7e,
	0x0d, 0x8c, 0x2a, 0x58, 0x14, 0x35, 0x2b, 0x0a, 0xff, 0xa5, 0x82, 0xe3, 0xf4, 0xbe, 0x86, 0xaa,
	0x54, 0x0d, 0x72, 0x2f, 0xaf, 0x7e, 0xe3, 0x6d, 0xd7, 0x72, 0xc5, 0x41, 0xdf, 0xc3, 0xcb, 0xef,
	0x90, 0xad, 0xf1, 0xe5, 0xe2, 0x75, 0x21, 0xae, 0xbe, 0x85, 0xaa, 0x59, 0x74, 0xb5, 0xb9, 0xc0,
	0xd5, 0xc7, 0x78, 0x75, 0x43, 0x97, 0xd5, 0xe2, 0xd4, 0x36, 0xd2, 0xd7, 0xe3, 0xbc, 0x09, 0x69,
	0x22, 0x14, 0x56, 0x47, 0xd2, 0x44, 0x0e, 0x0b, 0x2a, 0x95, 0x8a, 0x56, 0x54, 0xa7, 0x38, 0x95,
	0x56, 0x4e, 0x2a, 0x3f, 0x95, 0x60, 0x63, 0x52, 0xd6, 0xc8, 0x71, 0xe1, 0xb8, 0x4d, 0xe8, 0x87,
	0x36, 0x53, 0xb4, 0xf4, 0x13, 0x8c, 0xf9, 0x80, 0x1c, 0x8d, 0x63, 0x4a, 0x4d, 0x89, 0xda, 0xad,
	0x76, 0x4a, 0x4f, 0x90, 0xc5, 0x6f, 0x25, 0xd8, 0x30, 0xe7, 0xb1, 0x30, 0xdf, 0x82, 0xc5, 0x67,
	0xc8, 0xe2, 0x99, 0xfe, 0xe1, 0x78, 0x2e, 0x63, 0x69, 0x33, 0x66, 0x53, 0xc2, 0x26, 0x4c, 0x68,
	0xa1, 0x28, 0xd5, 0x56, 0x46, 0x7a, 0xc9, 0xc3, 0x59, 0x03, 0x3c, 0x49, 0xb5, 0xa8, 0x3d, 0x71,
	0xa9, 0x5a, 0x0b, 0x95, 0xea, 0x97, 0x12, 0xd4, 0xa7, 0xf4, 0x97, 0xbc, 0x9f, 0xfd, 0xf0, 0xc9,
	0x95, 0x7c, 0xad, 0x39, 0x1f, 0x28, 0xa5, 0x5c, 0x3f, 0x47, 0x4e, 0x1f, 0xe8, 0xcd, 0x05, 0x38,
	0x75, 0x5c, 0xc7, 0x7b, 0xd9, 0x29, 0xb5, 0x2e, 0xd4, 0x6f, 0x76, 0xa7, 0xfe, 0x29, 0x3f, 0x96,
	0xbf, 0x6e, 0xaa, 0x98, 0xf2, 0xf9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xb5, 0xd1, 0x32,
	0x4a, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PointsClient is the client API for Points service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PointsClient interface {
	// Gets a brand.
	GetBrand(ctx context.Context, in *GetBrandRequest, opts ...grpc.CallOption) (*Brand, error)
	// Sets a brand.
	SetBrand(ctx context.Context, in *SetBrandRequest, opts ...grpc.CallOption) (*Brand, error)
	// Deletes a brand.
	DeleteBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Gets a point.
	GetPoint(ctx context.Context, in *GetPointRequest, opts ...grpc.CallOption) (*Point, error)
	// Updates an existing point.
	UpdatePoint(ctx context.Context, in *UpdatePointRequest, opts ...grpc.CallOption) (*Point, error)
	// Deletes a point.
	DeletePoint(ctx context.Context, in *DeletePointRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Gets a tag.
	GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error)
	// Sets a tag.
	SetTag(ctx context.Context, in *SetTagRequest, opts ...grpc.CallOption) (*Tag, error)
	// Deletes a tag.
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Gets a point source.
	GetPointSource(ctx context.Context, in *GetPointSourceRequest, opts ...grpc.CallOption) (*PointSource, error)
	// Sets a point source.
	SetPointSource(ctx context.Context, in *SetPointSourceRequest, opts ...grpc.CallOption) (*PointSource, error)
	// Deletes a point source.
	DeletePointSource(ctx context.Context, in *DeletePointSourceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Associates point sources with a point.
	LinkPointSource(ctx context.Context, in *LinkPointSourceRequest, opts ...grpc.CallOption) (*LinkPointSourceResponse, error)
}

type pointsClient struct {
	cc *grpc.ClientConn
}

func NewPointsClient(cc *grpc.ClientConn) PointsClient {
	return &pointsClient{cc}
}

func (c *pointsClient) GetBrand(ctx context.Context, in *GetBrandRequest, opts ...grpc.CallOption) (*Brand, error) {
	out := new(Brand)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/GetBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) SetBrand(ctx context.Context, in *SetBrandRequest, opts ...grpc.CallOption) (*Brand, error) {
	out := new(Brand)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/SetBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) DeleteBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/DeleteBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) GetPoint(ctx context.Context, in *GetPointRequest, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/GetPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) UpdatePoint(ctx context.Context, in *UpdatePointRequest, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/UpdatePoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) DeletePoint(ctx context.Context, in *DeletePointRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/DeletePoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	out := new(Tag)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/GetTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) SetTag(ctx context.Context, in *SetTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	out := new(Tag)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/SetTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/DeleteTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) GetPointSource(ctx context.Context, in *GetPointSourceRequest, opts ...grpc.CallOption) (*PointSource, error) {
	out := new(PointSource)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/GetPointSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) SetPointSource(ctx context.Context, in *SetPointSourceRequest, opts ...grpc.CallOption) (*PointSource, error) {
	out := new(PointSource)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/SetPointSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) DeletePointSource(ctx context.Context, in *DeletePointSourceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/DeletePointSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsClient) LinkPointSource(ctx context.Context, in *LinkPointSourceRequest, opts ...grpc.CallOption) (*LinkPointSourceResponse, error) {
	out := new(LinkPointSourceResponse)
	err := c.cc.Invoke(ctx, "/topos.points.v1.Points/LinkPointSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointsServer is the server API for Points service.
type PointsServer interface {
	// Gets a brand.
	GetBrand(context.Context, *GetBrandRequest) (*Brand, error)
	// Sets a brand.
	SetBrand(context.Context, *SetBrandRequest) (*Brand, error)
	// Deletes a brand.
	DeleteBrand(context.Context, *DeleteBrandRequest) (*empty.Empty, error)
	// Gets a point.
	GetPoint(context.Context, *GetPointRequest) (*Point, error)
	// Updates an existing point.
	UpdatePoint(context.Context, *UpdatePointRequest) (*Point, error)
	// Deletes a point.
	DeletePoint(context.Context, *DeletePointRequest) (*empty.Empty, error)
	// Gets a tag.
	GetTag(context.Context, *GetTagRequest) (*Tag, error)
	// Sets a tag.
	SetTag(context.Context, *SetTagRequest) (*Tag, error)
	// Deletes a tag.
	DeleteTag(context.Context, *DeleteTagRequest) (*empty.Empty, error)
	// Gets a point source.
	GetPointSource(context.Context, *GetPointSourceRequest) (*PointSource, error)
	// Sets a point source.
	SetPointSource(context.Context, *SetPointSourceRequest) (*PointSource, error)
	// Deletes a point source.
	DeletePointSource(context.Context, *DeletePointSourceRequest) (*empty.Empty, error)
	// Associates point sources with a point.
	LinkPointSource(context.Context, *LinkPointSourceRequest) (*LinkPointSourceResponse, error)
}

func RegisterPointsServer(s *grpc.Server, srv PointsServer) {
	s.RegisterService(&_Points_serviceDesc, srv)
}

func _Points_GetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).GetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/GetBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).GetBrand(ctx, req.(*GetBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_SetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).SetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/SetBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).SetBrand(ctx, req.(*SetBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_DeleteBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).DeleteBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/DeleteBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).DeleteBrand(ctx, req.(*DeleteBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_GetPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).GetPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/GetPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).GetPoint(ctx, req.(*GetPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_UpdatePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).UpdatePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/UpdatePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).UpdatePoint(ctx, req.(*UpdatePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_DeletePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).DeletePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/DeletePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).DeletePoint(ctx, req.(*DeletePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/GetTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).GetTag(ctx, req.(*GetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_SetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).SetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/SetTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).SetTag(ctx, req.(*SetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/DeleteTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_GetPointSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).GetPointSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/GetPointSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).GetPointSource(ctx, req.(*GetPointSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_SetPointSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPointSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).SetPointSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/SetPointSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).SetPointSource(ctx, req.(*SetPointSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_DeletePointSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).DeletePointSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/DeletePointSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).DeletePointSource(ctx, req.(*DeletePointSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Points_LinkPointSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkPointSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServer).LinkPointSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.points.v1.Points/LinkPointSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServer).LinkPointSource(ctx, req.(*LinkPointSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Points_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topos.points.v1.Points",
	HandlerType: (*PointsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBrand",
			Handler:    _Points_GetBrand_Handler,
		},
		{
			MethodName: "SetBrand",
			Handler:    _Points_SetBrand_Handler,
		},
		{
			MethodName: "DeleteBrand",
			Handler:    _Points_DeleteBrand_Handler,
		},
		{
			MethodName: "GetPoint",
			Handler:    _Points_GetPoint_Handler,
		},
		{
			MethodName: "UpdatePoint",
			Handler:    _Points_UpdatePoint_Handler,
		},
		{
			MethodName: "DeletePoint",
			Handler:    _Points_DeletePoint_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _Points_GetTag_Handler,
		},
		{
			MethodName: "SetTag",
			Handler:    _Points_SetTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Points_DeleteTag_Handler,
		},
		{
			MethodName: "GetPointSource",
			Handler:    _Points_GetPointSource_Handler,
		},
		{
			MethodName: "SetPointSource",
			Handler:    _Points_SetPointSource_Handler,
		},
		{
			MethodName: "DeletePointSource",
			Handler:    _Points_DeletePointSource_Handler,
		},
		{
			MethodName: "LinkPointSource",
			Handler:    _Points_LinkPointSource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topos/points/v1/points.proto",
}
