# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topos/geometry/circle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from topos.geometry import latlng_pb2 as topos_dot_geometry_dot_latlng__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='topos/geometry/circle.proto',
  package='topos.geometry',
  syntax='proto3',
  serialized_options=b'Z9github.com/topos-ai/topos-apis/genproto/go/topos/geometry',
  serialized_pb=b'\n\x1btopos/geometry/circle.proto\x12\x0etopos.geometry\x1a\x1btopos/geometry/latlng.proto\"@\n\x06\x43ircle\x12&\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x16.topos.geometry.LatLng\x12\x0e\n\x06radius\x18\x02 \x01(\x01\x42;Z9github.com/topos-ai/topos-apis/genproto/go/topos/geometryb\x06proto3'
  ,
  dependencies=[topos_dot_geometry_dot_latlng__pb2.DESCRIPTOR,])




_CIRCLE = _descriptor.Descriptor(
  name='Circle',
  full_name='topos.geometry.Circle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='center', full_name='topos.geometry.Circle.center', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='topos.geometry.Circle.radius', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=140,
)

_CIRCLE.fields_by_name['center'].message_type = topos_dot_geometry_dot_latlng__pb2._LATLNG
DESCRIPTOR.message_types_by_name['Circle'] = _CIRCLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Circle = _reflection.GeneratedProtocolMessageType('Circle', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLE,
  '__module__' : 'topos.geometry.circle_pb2'
  # @@protoc_insertion_point(class_scope:topos.geometry.Circle)
  })
_sym_db.RegisterMessage(Circle)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
