// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topos/timeseries/v1/time-series.proto

package timeseries

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Day int32

const (
	Day_MON  Day = 0
	Day_TUES Day = 1
	Day_WED  Day = 2
	Day_THU  Day = 3
	Day_FRI  Day = 4
	Day_SAT  Day = 5
	Day_SUN  Day = 6
)

var Day_name = map[int32]string{
	0: "MON",
	1: "TUES",
	2: "WED",
	3: "THU",
	4: "FRI",
	5: "SAT",
	6: "SUN",
}

var Day_value = map[string]int32{
	"MON":  0,
	"TUES": 1,
	"WED":  2,
	"THU":  3,
	"FRI":  4,
	"SAT":  5,
	"SUN":  6,
}

func (x Day) String() string {
	return proto.EnumName(Day_name, int32(x))
}

func (Day) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{0}
}

type TimePeriod int32

const (
	TimePeriod_WEEKDAY TimePeriod = 0
	TimePeriod_WEEKEND TimePeriod = 1
)

var TimePeriod_name = map[int32]string{
	0: "WEEKDAY",
	1: "WEEKEND",
}

var TimePeriod_value = map[string]int32{
	"WEEKDAY": 0,
	"WEEKEND": 1,
}

func (x TimePeriod) String() string {
	return proto.EnumName(TimePeriod_name, int32(x))
}

func (TimePeriod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{1}
}

type TimeSeriesFeature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	SamplingInterval     int64    `protobuf:"varint,5,opt,name=sampling_interval,json=samplingInterval,proto3" json:"sampling_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeSeriesFeature) Reset()         { *m = TimeSeriesFeature{} }
func (m *TimeSeriesFeature) String() string { return proto.CompactTextString(m) }
func (*TimeSeriesFeature) ProtoMessage()    {}
func (*TimeSeriesFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{0}
}

func (m *TimeSeriesFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeriesFeature.Unmarshal(m, b)
}
func (m *TimeSeriesFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeriesFeature.Marshal(b, m, deterministic)
}
func (m *TimeSeriesFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeriesFeature.Merge(m, src)
}
func (m *TimeSeriesFeature) XXX_Size() int {
	return xxx_messageInfo_TimeSeriesFeature.Size(m)
}
func (m *TimeSeriesFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeriesFeature.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeriesFeature proto.InternalMessageInfo

func (m *TimeSeriesFeature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TimeSeriesFeature) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *TimeSeriesFeature) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TimeSeriesFeature) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TimeSeriesFeature) GetSamplingInterval() int64 {
	if m != nil {
		return m.SamplingInterval
	}
	return 0
}

type TimeSeriesBin struct {
	RegionId             string   `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	FeatureName          string   `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Day                  Day      `protobuf:"varint,3,opt,name=day,proto3,enum=topos.timeseries.v1.Day" json:"day,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Value                int64    `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeSeriesBin) Reset()         { *m = TimeSeriesBin{} }
func (m *TimeSeriesBin) String() string { return proto.CompactTextString(m) }
func (*TimeSeriesBin) ProtoMessage()    {}
func (*TimeSeriesBin) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{1}
}

func (m *TimeSeriesBin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeriesBin.Unmarshal(m, b)
}
func (m *TimeSeriesBin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeriesBin.Marshal(b, m, deterministic)
}
func (m *TimeSeriesBin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeriesBin.Merge(m, src)
}
func (m *TimeSeriesBin) XXX_Size() int {
	return xxx_messageInfo_TimeSeriesBin.Size(m)
}
func (m *TimeSeriesBin) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeriesBin.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeriesBin proto.InternalMessageInfo

func (m *TimeSeriesBin) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *TimeSeriesBin) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *TimeSeriesBin) GetDay() Day {
	if m != nil {
		return m.Day
	}
	return Day_MON
}

func (m *TimeSeriesBin) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TimeSeriesBin) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TimeSeriesAverage struct {
	RegionId             string     `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	FeatureName          string     `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Period               TimePeriod `protobuf:"varint,3,opt,name=period,proto3,enum=topos.timeseries.v1.TimePeriod" json:"period,omitempty"`
	Value                []int64    `protobuf:"varint,4,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimeSeriesAverage) Reset()         { *m = TimeSeriesAverage{} }
func (m *TimeSeriesAverage) String() string { return proto.CompactTextString(m) }
func (*TimeSeriesAverage) ProtoMessage()    {}
func (*TimeSeriesAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{2}
}

func (m *TimeSeriesAverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeriesAverage.Unmarshal(m, b)
}
func (m *TimeSeriesAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeriesAverage.Marshal(b, m, deterministic)
}
func (m *TimeSeriesAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeriesAverage.Merge(m, src)
}
func (m *TimeSeriesAverage) XXX_Size() int {
	return xxx_messageInfo_TimeSeriesAverage.Size(m)
}
func (m *TimeSeriesAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeriesAverage.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeriesAverage proto.InternalMessageInfo

func (m *TimeSeriesAverage) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *TimeSeriesAverage) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *TimeSeriesAverage) GetPeriod() TimePeriod {
	if m != nil {
		return m.Period
	}
	return TimePeriod_WEEKDAY
}

func (m *TimeSeriesAverage) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type TimeSeriesValues struct {
	Values               []int64  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeSeriesValues) Reset()         { *m = TimeSeriesValues{} }
func (m *TimeSeriesValues) String() string { return proto.CompactTextString(m) }
func (*TimeSeriesValues) ProtoMessage()    {}
func (*TimeSeriesValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{3}
}

func (m *TimeSeriesValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeriesValues.Unmarshal(m, b)
}
func (m *TimeSeriesValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeriesValues.Marshal(b, m, deterministic)
}
func (m *TimeSeriesValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeriesValues.Merge(m, src)
}
func (m *TimeSeriesValues) XXX_Size() int {
	return xxx_messageInfo_TimeSeriesValues.Size(m)
}
func (m *TimeSeriesValues) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeriesValues.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeriesValues proto.InternalMessageInfo

func (m *TimeSeriesValues) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetTimeSeriesBinRequest struct {
	RegionName           string   `protobuf:"bytes,1,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	FeatureName          string   `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Day                  Day      `protobuf:"varint,3,opt,name=day,proto3,enum=topos.timeseries.v1.Day" json:"day,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimeSeriesBinRequest) Reset()         { *m = GetTimeSeriesBinRequest{} }
func (m *GetTimeSeriesBinRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeSeriesBinRequest) ProtoMessage()    {}
func (*GetTimeSeriesBinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{4}
}

func (m *GetTimeSeriesBinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeSeriesBinRequest.Unmarshal(m, b)
}
func (m *GetTimeSeriesBinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeSeriesBinRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeSeriesBinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeSeriesBinRequest.Merge(m, src)
}
func (m *GetTimeSeriesBinRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeSeriesBinRequest.Size(m)
}
func (m *GetTimeSeriesBinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeSeriesBinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeSeriesBinRequest proto.InternalMessageInfo

func (m *GetTimeSeriesBinRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *GetTimeSeriesBinRequest) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *GetTimeSeriesBinRequest) GetDay() Day {
	if m != nil {
		return m.Day
	}
	return Day_MON
}

func (m *GetTimeSeriesBinRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetTimeSeriesBinRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GetTimeSeriesBinBulkRequest struct {
	FeatureName          string   `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	RegionNames          []string `protobuf:"bytes,2,rep,name=region_names,json=regionNames,proto3" json:"region_names,omitempty"`
	Day                  Day      `protobuf:"varint,3,opt,name=day,proto3,enum=topos.timeseries.v1.Day" json:"day,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimeSeriesBinBulkRequest) Reset()         { *m = GetTimeSeriesBinBulkRequest{} }
func (m *GetTimeSeriesBinBulkRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeSeriesBinBulkRequest) ProtoMessage()    {}
func (*GetTimeSeriesBinBulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{5}
}

func (m *GetTimeSeriesBinBulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeSeriesBinBulkRequest.Unmarshal(m, b)
}
func (m *GetTimeSeriesBinBulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeSeriesBinBulkRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeSeriesBinBulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeSeriesBinBulkRequest.Merge(m, src)
}
func (m *GetTimeSeriesBinBulkRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeSeriesBinBulkRequest.Size(m)
}
func (m *GetTimeSeriesBinBulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeSeriesBinBulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeSeriesBinBulkRequest proto.InternalMessageInfo

func (m *GetTimeSeriesBinBulkRequest) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *GetTimeSeriesBinBulkRequest) GetRegionNames() []string {
	if m != nil {
		return m.RegionNames
	}
	return nil
}

func (m *GetTimeSeriesBinBulkRequest) GetDay() Day {
	if m != nil {
		return m.Day
	}
	return Day_MON
}

func (m *GetTimeSeriesBinBulkRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetTimeSeriesBinBulkRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GetTimeSeriesAverageBulkRequest struct {
	FeatureName          string     `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	RegionNames          []string   `protobuf:"bytes,2,rep,name=region_names,json=regionNames,proto3" json:"region_names,omitempty"`
	Period               TimePeriod `protobuf:"varint,3,opt,name=period,proto3,enum=topos.timeseries.v1.TimePeriod" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetTimeSeriesAverageBulkRequest) Reset()         { *m = GetTimeSeriesAverageBulkRequest{} }
func (m *GetTimeSeriesAverageBulkRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeSeriesAverageBulkRequest) ProtoMessage()    {}
func (*GetTimeSeriesAverageBulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{6}
}

func (m *GetTimeSeriesAverageBulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeSeriesAverageBulkRequest.Unmarshal(m, b)
}
func (m *GetTimeSeriesAverageBulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeSeriesAverageBulkRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeSeriesAverageBulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeSeriesAverageBulkRequest.Merge(m, src)
}
func (m *GetTimeSeriesAverageBulkRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeSeriesAverageBulkRequest.Size(m)
}
func (m *GetTimeSeriesAverageBulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeSeriesAverageBulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeSeriesAverageBulkRequest proto.InternalMessageInfo

func (m *GetTimeSeriesAverageBulkRequest) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *GetTimeSeriesAverageBulkRequest) GetRegionNames() []string {
	if m != nil {
		return m.RegionNames
	}
	return nil
}

func (m *GetTimeSeriesAverageBulkRequest) GetPeriod() TimePeriod {
	if m != nil {
		return m.Period
	}
	return TimePeriod_WEEKDAY
}

type SetTimeSeriesAverageBulkRequest struct {
	Averages             []*TimeSeriesAverage `protobuf:"bytes,1,rep,name=averages,proto3" json:"averages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetTimeSeriesAverageBulkRequest) Reset()         { *m = SetTimeSeriesAverageBulkRequest{} }
func (m *SetTimeSeriesAverageBulkRequest) String() string { return proto.CompactTextString(m) }
func (*SetTimeSeriesAverageBulkRequest) ProtoMessage()    {}
func (*SetTimeSeriesAverageBulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{7}
}

func (m *SetTimeSeriesAverageBulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimeSeriesAverageBulkRequest.Unmarshal(m, b)
}
func (m *SetTimeSeriesAverageBulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimeSeriesAverageBulkRequest.Marshal(b, m, deterministic)
}
func (m *SetTimeSeriesAverageBulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimeSeriesAverageBulkRequest.Merge(m, src)
}
func (m *SetTimeSeriesAverageBulkRequest) XXX_Size() int {
	return xxx_messageInfo_SetTimeSeriesAverageBulkRequest.Size(m)
}
func (m *SetTimeSeriesAverageBulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimeSeriesAverageBulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimeSeriesAverageBulkRequest proto.InternalMessageInfo

func (m *SetTimeSeriesAverageBulkRequest) GetAverages() []*TimeSeriesAverage {
	if m != nil {
		return m.Averages
	}
	return nil
}

type GetTimeSeriesBinBulkResponse struct {
	TimeSeries           map[string]*TimeSeriesValues `protobuf:"bytes,1,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetTimeSeriesBinBulkResponse) Reset()         { *m = GetTimeSeriesBinBulkResponse{} }
func (m *GetTimeSeriesBinBulkResponse) String() string { return proto.CompactTextString(m) }
func (*GetTimeSeriesBinBulkResponse) ProtoMessage()    {}
func (*GetTimeSeriesBinBulkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{8}
}

func (m *GetTimeSeriesBinBulkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeSeriesBinBulkResponse.Unmarshal(m, b)
}
func (m *GetTimeSeriesBinBulkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeSeriesBinBulkResponse.Marshal(b, m, deterministic)
}
func (m *GetTimeSeriesBinBulkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeSeriesBinBulkResponse.Merge(m, src)
}
func (m *GetTimeSeriesBinBulkResponse) XXX_Size() int {
	return xxx_messageInfo_GetTimeSeriesBinBulkResponse.Size(m)
}
func (m *GetTimeSeriesBinBulkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeSeriesBinBulkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeSeriesBinBulkResponse proto.InternalMessageInfo

func (m *GetTimeSeriesBinBulkResponse) GetTimeSeries() map[string]*TimeSeriesValues {
	if m != nil {
		return m.TimeSeries
	}
	return nil
}

type SetTimeSeriesFeatureRequest struct {
	Feature              *TimeSeriesFeature `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SetTimeSeriesFeatureRequest) Reset()         { *m = SetTimeSeriesFeatureRequest{} }
func (m *SetTimeSeriesFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*SetTimeSeriesFeatureRequest) ProtoMessage()    {}
func (*SetTimeSeriesFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{9}
}

func (m *SetTimeSeriesFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimeSeriesFeatureRequest.Unmarshal(m, b)
}
func (m *SetTimeSeriesFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimeSeriesFeatureRequest.Marshal(b, m, deterministic)
}
func (m *SetTimeSeriesFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimeSeriesFeatureRequest.Merge(m, src)
}
func (m *SetTimeSeriesFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_SetTimeSeriesFeatureRequest.Size(m)
}
func (m *SetTimeSeriesFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimeSeriesFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimeSeriesFeatureRequest proto.InternalMessageInfo

func (m *SetTimeSeriesFeatureRequest) GetFeature() *TimeSeriesFeature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type SetTimeSeriesBinRequest struct {
	Bin                  *TimeSeriesBin `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetTimeSeriesBinRequest) Reset()         { *m = SetTimeSeriesBinRequest{} }
func (m *SetTimeSeriesBinRequest) String() string { return proto.CompactTextString(m) }
func (*SetTimeSeriesBinRequest) ProtoMessage()    {}
func (*SetTimeSeriesBinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{10}
}

func (m *SetTimeSeriesBinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimeSeriesBinRequest.Unmarshal(m, b)
}
func (m *SetTimeSeriesBinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimeSeriesBinRequest.Marshal(b, m, deterministic)
}
func (m *SetTimeSeriesBinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimeSeriesBinRequest.Merge(m, src)
}
func (m *SetTimeSeriesBinRequest) XXX_Size() int {
	return xxx_messageInfo_SetTimeSeriesBinRequest.Size(m)
}
func (m *SetTimeSeriesBinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimeSeriesBinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimeSeriesBinRequest proto.InternalMessageInfo

func (m *SetTimeSeriesBinRequest) GetBin() *TimeSeriesBin {
	if m != nil {
		return m.Bin
	}
	return nil
}

type DeleteTimeSeriesBinRequest struct {
	Bin                  *TimeSeriesBin `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteTimeSeriesBinRequest) Reset()         { *m = DeleteTimeSeriesBinRequest{} }
func (m *DeleteTimeSeriesBinRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTimeSeriesBinRequest) ProtoMessage()    {}
func (*DeleteTimeSeriesBinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{11}
}

func (m *DeleteTimeSeriesBinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTimeSeriesBinRequest.Unmarshal(m, b)
}
func (m *DeleteTimeSeriesBinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTimeSeriesBinRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTimeSeriesBinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTimeSeriesBinRequest.Merge(m, src)
}
func (m *DeleteTimeSeriesBinRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTimeSeriesBinRequest.Size(m)
}
func (m *DeleteTimeSeriesBinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTimeSeriesBinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTimeSeriesBinRequest proto.InternalMessageInfo

func (m *DeleteTimeSeriesBinRequest) GetBin() *TimeSeriesBin {
	if m != nil {
		return m.Bin
	}
	return nil
}

type DeleteTimeSeriesFeatureRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTimeSeriesFeatureRequest) Reset()         { *m = DeleteTimeSeriesFeatureRequest{} }
func (m *DeleteTimeSeriesFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTimeSeriesFeatureRequest) ProtoMessage()    {}
func (*DeleteTimeSeriesFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{12}
}

func (m *DeleteTimeSeriesFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTimeSeriesFeatureRequest.Unmarshal(m, b)
}
func (m *DeleteTimeSeriesFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTimeSeriesFeatureRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTimeSeriesFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTimeSeriesFeatureRequest.Merge(m, src)
}
func (m *DeleteTimeSeriesFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTimeSeriesFeatureRequest.Size(m)
}
func (m *DeleteTimeSeriesFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTimeSeriesFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTimeSeriesFeatureRequest proto.InternalMessageInfo

func (m *DeleteTimeSeriesFeatureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListTimeSeriesFeaturesRequest struct {
	// The maximum number of items to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTimeSeriesFeaturesRequest) Reset()         { *m = ListTimeSeriesFeaturesRequest{} }
func (m *ListTimeSeriesFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*ListTimeSeriesFeaturesRequest) ProtoMessage()    {}
func (*ListTimeSeriesFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{13}
}

func (m *ListTimeSeriesFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTimeSeriesFeaturesRequest.Unmarshal(m, b)
}
func (m *ListTimeSeriesFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTimeSeriesFeaturesRequest.Marshal(b, m, deterministic)
}
func (m *ListTimeSeriesFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTimeSeriesFeaturesRequest.Merge(m, src)
}
func (m *ListTimeSeriesFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_ListTimeSeriesFeaturesRequest.Size(m)
}
func (m *ListTimeSeriesFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTimeSeriesFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTimeSeriesFeaturesRequest proto.InternalMessageInfo

func (m *ListTimeSeriesFeaturesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListTimeSeriesFeaturesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListTimeSeriesFeaturesResponse struct {
	Features []*TimeSeriesFeature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more
	// results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTimeSeriesFeaturesResponse) Reset()         { *m = ListTimeSeriesFeaturesResponse{} }
func (m *ListTimeSeriesFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*ListTimeSeriesFeaturesResponse) ProtoMessage()    {}
func (*ListTimeSeriesFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f49efa5087395, []int{14}
}

func (m *ListTimeSeriesFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTimeSeriesFeaturesResponse.Unmarshal(m, b)
}
func (m *ListTimeSeriesFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTimeSeriesFeaturesResponse.Marshal(b, m, deterministic)
}
func (m *ListTimeSeriesFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTimeSeriesFeaturesResponse.Merge(m, src)
}
func (m *ListTimeSeriesFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_ListTimeSeriesFeaturesResponse.Size(m)
}
func (m *ListTimeSeriesFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTimeSeriesFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTimeSeriesFeaturesResponse proto.InternalMessageInfo

func (m *ListTimeSeriesFeaturesResponse) GetFeatures() []*TimeSeriesFeature {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *ListTimeSeriesFeaturesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterEnum("topos.timeseries.v1.Day", Day_name, Day_value)
	proto.RegisterEnum("topos.timeseries.v1.TimePeriod", TimePeriod_name, TimePeriod_value)
	proto.RegisterType((*TimeSeriesFeature)(nil), "topos.timeseries.v1.TimeSeriesFeature")
	proto.RegisterType((*TimeSeriesBin)(nil), "topos.timeseries.v1.TimeSeriesBin")
	proto.RegisterType((*TimeSeriesAverage)(nil), "topos.timeseries.v1.TimeSeriesAverage")
	proto.RegisterType((*TimeSeriesValues)(nil), "topos.timeseries.v1.TimeSeriesValues")
	proto.RegisterType((*GetTimeSeriesBinRequest)(nil), "topos.timeseries.v1.GetTimeSeriesBinRequest")
	proto.RegisterType((*GetTimeSeriesBinBulkRequest)(nil), "topos.timeseries.v1.GetTimeSeriesBinBulkRequest")
	proto.RegisterType((*GetTimeSeriesAverageBulkRequest)(nil), "topos.timeseries.v1.GetTimeSeriesAverageBulkRequest")
	proto.RegisterType((*SetTimeSeriesAverageBulkRequest)(nil), "topos.timeseries.v1.SetTimeSeriesAverageBulkRequest")
	proto.RegisterType((*GetTimeSeriesBinBulkResponse)(nil), "topos.timeseries.v1.GetTimeSeriesBinBulkResponse")
	proto.RegisterMapType((map[string]*TimeSeriesValues)(nil), "topos.timeseries.v1.GetTimeSeriesBinBulkResponse.TimeSeriesEntry")
	proto.RegisterType((*SetTimeSeriesFeatureRequest)(nil), "topos.timeseries.v1.SetTimeSeriesFeatureRequest")
	proto.RegisterType((*SetTimeSeriesBinRequest)(nil), "topos.timeseries.v1.SetTimeSeriesBinRequest")
	proto.RegisterType((*DeleteTimeSeriesBinRequest)(nil), "topos.timeseries.v1.DeleteTimeSeriesBinRequest")
	proto.RegisterType((*DeleteTimeSeriesFeatureRequest)(nil), "topos.timeseries.v1.DeleteTimeSeriesFeatureRequest")
	proto.RegisterType((*ListTimeSeriesFeaturesRequest)(nil), "topos.timeseries.v1.ListTimeSeriesFeaturesRequest")
	proto.RegisterType((*ListTimeSeriesFeaturesResponse)(nil), "topos.timeseries.v1.ListTimeSeriesFeaturesResponse")
}

func init() {
	proto.RegisterFile("topos/timeseries/v1/time-series.proto", fileDescriptor_721f49efa5087395)
}

var fileDescriptor_721f49efa5087395 = []byte{
	// 1142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x97, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xc0, 0x3b, 0x71, 0x3e, 0x9c, 0xe7, 0x96, 0x6e, 0x27, 0x51, 0xb2, 0xb5, 0xf3, 0xe1, 0x8c,
	0x68, 0x5a, 0x19, 0xb2, 0x4b, 0x3e, 0x24, 0x50, 0x2a, 0x24, 0x12, 0xd9, 0x85, 0xa8, 0x90, 0x56,
	0x76, 0x42, 0x05, 0x1c, 0xac, 0x75, 0x76, 0x6a, 0x46, 0xb1, 0x77, 0x97, 0x9d, 0x75, 0x84, 0x1b,
	0xf5, 0x82, 0x7a, 0x03, 0x24, 0x24, 0xae, 0x48, 0x20, 0xb8, 0x72, 0x80, 0xbf, 0x81, 0x13, 0x67,
	0xfe, 0x02, 0x24, 0x0e, 0xfc, 0x19, 0xd5, 0xcc, 0xce, 0xda, 0xf1, 0x66, 0x37, 0x76, 0xda, 0xaa,
	0xb7, 0x99, 0xf7, 0xde, 0xbc, 0xf9, 0xcd, 0xfb, 0x5a, 0x1b, 0x6e, 0x05, 0xae, 0xe7, 0x72, 0x33,
	0x60, 0x6d, 0xca, 0xa9, 0xcf, 0x28, 0x37, 0x4f, 0xd6, 0xe5, 0x6e, 0x2d, 0xdc, 0x1a, 0x9e, 0xef,
	0x06, 0x2e, 0x9e, 0x91, 0x66, 0x46, 0xdf, 0xcc, 0x38, 0x59, 0xcf, 0x2f, 0x34, 0x5d, 0xb7, 0xd9,
	0xa2, 0xa6, 0xe5, 0x31, 0xd3, 0x72, 0x1c, 0x37, 0xb0, 0x02, 0xe6, 0x3a, 0xea, 0x48, 0xbe, 0xa0,
	0xb4, 0x72, 0xd7, 0xe8, 0x3c, 0x36, 0x69, 0xdb, 0x0b, 0xba, 0xa1, 0x92, 0xfc, 0x89, 0xe0, 0xc6,
	0x01, 0x6b, 0xd3, 0x9a, 0x74, 0x76, 0x8f, 0x5a, 0x41, 0xc7, 0xa7, 0x18, 0xc3, 0xb8, 0x63, 0xb5,
	0xa9, 0x8e, 0x8a, 0xe8, 0xce, 0x74, 0x55, 0xae, 0xf1, 0x0a, 0x5c, 0xb5, 0x19, 0xf7, 0x5a, 0x56,
	0xb7, 0x2e, 0x75, 0x63, 0x52, 0x97, 0x53, 0xb2, 0x7d, 0x61, 0x52, 0x84, 0x9c, 0x4d, 0xf9, 0x91,
	0xcf, 0x3c, 0x71, 0xbf, 0x9e, 0x51, 0x16, 0x7d, 0x11, 0x9e, 0x83, 0x49, 0xee, 0x76, 0xfc, 0x23,
	0xaa, 0x8f, 0x4b, 0xa5, 0xda, 0xe1, 0xb7, 0xe0, 0x06, 0xb7, 0xda, 0x5e, 0x8b, 0x39, 0xcd, 0x3a,
	0x73, 0x02, 0xea, 0x9f, 0x58, 0x2d, 0x7d, 0xa2, 0x88, 0xee, 0x64, 0xaa, 0x5a, 0xa4, 0xd8, 0x53,
	0x72, 0xf2, 0x07, 0x82, 0x6b, 0x7d, 0xe6, 0x5d, 0xe6, 0xe0, 0x02, 0x4c, 0xfb, 0xb4, 0xc9, 0x5c,
	0xa7, 0xce, 0x6c, 0x05, 0x9d, 0x0d, 0x05, 0x7b, 0xb6, 0x00, 0x7f, 0x1c, 0xbe, 0x6b, 0x00, 0x5c,
	0xc9, 0x24, 0x78, 0x09, 0x32, 0xb6, 0xd5, 0x95, 0xc0, 0x6f, 0x6c, 0xe8, 0x46, 0x42, 0x8c, 0x8d,
	0xb2, 0xd5, 0xad, 0x0a, 0x23, 0xbc, 0x08, 0xc0, 0x03, 0xcb, 0x0f, 0xea, 0x42, 0xaf, 0x9e, 0x31,
	0x2d, 0x25, 0x82, 0x09, 0xcf, 0xc2, 0xc4, 0x89, 0xd5, 0xea, 0x50, 0x7d, 0x52, 0xd2, 0x87, 0x1b,
	0xf2, 0xeb, 0x40, 0x98, 0x77, 0x4e, 0xa8, 0x6f, 0x35, 0xe9, 0x4b, 0x63, 0xbf, 0x0b, 0x93, 0x1e,
	0xf5, 0x99, 0x6b, 0x2b, 0xf2, 0xe5, 0x44, 0x72, 0x71, 0xef, 0x43, 0x69, 0x56, 0x55, 0xe6, 0x7d,
	0xc8, 0xf1, 0x62, 0xa6, 0x0f, 0x59, 0x02, 0xad, 0xcf, 0xf8, 0xa9, 0x10, 0x71, 0x91, 0x30, 0xa9,
	0xe4, 0x3a, 0x92, 0xa6, 0x6a, 0x47, 0xfe, 0x42, 0x30, 0xff, 0x21, 0x0d, 0x06, 0xd2, 0x50, 0xa5,
	0x5f, 0x75, 0x28, 0x0f, 0xf0, 0x32, 0xe4, 0xd4, 0xb3, 0xce, 0x14, 0x11, 0x84, 0xa2, 0x7d, 0x55,
	0x4a, 0xaf, 0x31, 0x23, 0x37, 0x21, 0x4b, 0x1d, 0x3b, 0x54, 0x4e, 0x48, 0xe5, 0x14, 0x75, 0x6c,
	0xa1, 0x22, 0x7f, 0x23, 0x28, 0xc4, 0x5f, 0xb1, 0xdb, 0x69, 0x1d, 0x47, 0x2f, 0x89, 0x83, 0xa2,
	0xf3, 0xa0, 0x2b, 0x70, 0xf5, 0xcc, 0x63, 0xb9, 0x3e, 0x56, 0xcc, 0x08, 0x93, 0xfe, 0x6b, 0xf9,
	0x6b, 0x7a, 0xcb, 0x2f, 0x08, 0x96, 0x07, 0xde, 0xa2, 0xaa, 0xec, 0xd5, 0xbf, 0xe7, 0x45, 0xcb,
	0x8e, 0x50, 0x58, 0xae, 0x0d, 0x21, 0xdc, 0x85, 0xac, 0x15, 0x4a, 0xc3, 0x8a, 0xcb, 0x6d, 0xac,
	0xa6, 0x7a, 0x1f, 0x70, 0x52, 0xed, 0x9d, 0x23, 0xff, 0x23, 0x58, 0x48, 0xce, 0x2a, 0xf7, 0x5c,
	0x87, 0x53, 0xdc, 0x80, 0x9c, 0xf0, 0x56, 0x0f, 0xdd, 0xa9, 0x7b, 0x76, 0x12, 0xef, 0xb9, 0xc8,
	0xcf, 0x19, 0x88, 0x8a, 0x13, 0xf8, 0xdd, 0x2a, 0x04, 0x3d, 0x41, 0xde, 0x86, 0xeb, 0x31, 0x35,
	0xd6, 0x20, 0x73, 0x4c, 0xbb, 0x2a, 0xe8, 0x62, 0x89, 0xef, 0x46, 0x7d, 0x28, 0x3a, 0x20, 0xb7,
	0x71, 0x6b, 0xc8, 0x53, 0xc3, 0x9e, 0x54, 0xed, 0xba, 0x3d, 0xf6, 0x1e, 0x22, 0x75, 0x28, 0x0c,
	0x44, 0x54, 0x0d, 0xf0, 0x28, 0x9a, 0x1f, 0xc0, 0x94, 0xca, 0xad, 0xbc, 0x75, 0x78, 0x30, 0xa3,
	0xf3, 0xd1, 0x31, 0xf2, 0x00, 0xe6, 0x6b, 0x29, 0x6d, 0xbe, 0x05, 0x99, 0x06, 0x73, 0x94, 0x63,
	0x32, 0xc4, 0xb1, 0x38, 0x27, 0xcc, 0x49, 0x15, 0xf2, 0x65, 0xda, 0xa2, 0x01, 0x7d, 0x85, 0x3e,
	0xb7, 0x60, 0x29, 0xee, 0x33, 0x16, 0x88, 0x84, 0x0f, 0x1a, 0xf9, 0x02, 0x16, 0x3f, 0x66, 0xfc,
	0x7c, 0xf0, 0x78, 0x74, 0xa8, 0x00, 0xd3, 0x9e, 0xd5, 0xa4, 0x75, 0xce, 0x9e, 0x84, 0x27, 0x27,
	0xaa, 0x59, 0x21, 0xa8, 0xb1, 0x27, 0x54, 0x34, 0xaa, 0x54, 0x06, 0xee, 0x31, 0x75, 0xd4, 0x04,
	0x93, 0xe6, 0x07, 0x42, 0x40, 0xbe, 0x43, 0xb0, 0x94, 0xe6, 0x5d, 0x55, 0xe1, 0x2e, 0x64, 0x55,
	0x94, 0x47, 0x2d, 0xf5, 0xe8, 0x51, 0xbd, 0x73, 0x78, 0x15, 0xae, 0x3b, 0xf4, 0xeb, 0xa0, 0x7e,
	0x0e, 0xe5, 0x9a, 0x10, 0x3f, 0x8c, 0x70, 0x4a, 0x15, 0xc8, 0x94, 0xad, 0x2e, 0x9e, 0x82, 0xcc,
	0x27, 0x0f, 0xf6, 0xb5, 0x2b, 0x38, 0x0b, 0xe3, 0x07, 0x87, 0x95, 0x9a, 0x86, 0x84, 0xe8, 0x51,
	0xa5, 0xac, 0x8d, 0x89, 0xc5, 0xc1, 0x47, 0x87, 0x5a, 0x46, 0x2c, 0xee, 0x55, 0xf7, 0xb4, 0x71,
	0xb1, 0xa8, 0xed, 0x1c, 0x68, 0x13, 0x72, 0x71, 0xb8, 0xaf, 0x4d, 0x96, 0x56, 0x01, 0xfa, 0x6d,
	0x8d, 0x73, 0x30, 0xf5, 0xa8, 0x52, 0xb9, 0x5f, 0xde, 0xf9, 0x4c, 0xbb, 0x12, 0x6d, 0x2a, 0xfb,
	0x65, 0x0d, 0x6d, 0xfc, 0x0b, 0xa1, 0x61, 0x88, 0x8d, 0x9f, 0x21, 0xd0, 0xe2, 0x8d, 0x84, 0xdf,
	0x1e, 0xa9, 0xdf, 0x54, 0x2e, 0xf2, 0x23, 0xd4, 0x02, 0x59, 0xfa, 0xe6, 0x9f, 0xff, 0x7e, 0x1c,
	0xd3, 0xc9, 0x4c, 0xec, 0xa7, 0xd3, 0x5a, 0x83, 0x39, 0xdb, 0xa8, 0x84, 0x7f, 0x42, 0x30, 0x9b,
	0xd4, 0xcf, 0xf8, 0x9d, 0x4b, 0xb4, 0x7e, 0x88, 0xb3, 0x7e, 0xe9, 0x61, 0x41, 0x96, 0x25, 0xdd,
	0x4d, 0x32, 0x1b, 0xa3, 0x33, 0x1b, 0x9d, 0xd6, 0xb1, 0xc0, 0xfb, 0x1d, 0x81, 0x9e, 0x36, 0xc0,
	0xf1, 0xd6, 0xf0, 0x0b, 0xcf, 0x4f, 0xd3, 0x17, 0xc1, 0xbc, 0x2d, 0x31, 0x57, 0xc8, 0x42, 0x12,
	0xa6, 0xa9, 0x66, 0xac, 0xc0, 0xfd, 0x0d, 0xc1, 0x5c, 0x72, 0x85, 0xe3, 0x8d, 0xc4, 0x6b, 0x2f,
	0x6c, 0xb6, 0xfc, 0xe6, 0xa5, 0xce, 0x28, 0xd8, 0xa2, 0x84, 0xcd, 0x63, 0x3d, 0x9e, 0xf1, 0x5e,
	0x83, 0xfc, 0x80, 0x40, 0xab, 0x8d, 0x56, 0x7a, 0xb5, 0x97, 0x28, 0xbd, 0x92, 0x04, 0x79, 0x93,
	0x2c, 0x0a, 0x90, 0xd3, 0x06, 0x73, 0x8c, 0xde, 0x0f, 0xbb, 0xf7, 0x1b, 0xcc, 0x31, 0x4b, 0x4f,
	0xb7, 0x39, 0x0d, 0xb6, 0xc5, 0xb4, 0xc2, 0x3f, 0x23, 0x98, 0x4d, 0x1a, 0xda, 0x29, 0x65, 0x78,
	0xc1, 0x7c, 0xcf, 0x8f, 0x38, 0x30, 0xc8, 0x9a, 0xc4, 0xbb, 0x1d, 0x26, 0xf5, 0x54, 0x05, 0xc7,
	0x10, 0x53, 0xf0, 0x2c, 0x5d, 0x34, 0xf4, 0xf1, 0xb7, 0x08, 0xf4, 0xda, 0xe5, 0x2a, 0x71, 0xc8,
	0x77, 0x3d, 0x3f, 0x67, 0x84, 0xff, 0x42, 0x8c, 0xe8, 0x5f, 0x88, 0x51, 0x11, 0xff, 0x42, 0xc8,
	0x8a, 0x24, 0x2b, 0x84, 0x5d, 0x31, 0x50, 0x62, 0xbd, 0x78, 0x7d, 0x8f, 0x60, 0x26, 0xe1, 0x93,
	0x81, 0xcd, 0xe4, 0x5f, 0x52, 0xa9, 0x1f, 0x97, 0x54, 0x86, 0x28, 0x3a, 0xc5, 0xf4, 0xe4, 0xd9,
	0xd2, 0x6b, 0xc8, 0xf3, 0x0c, 0xc1, 0x7c, 0xca, 0xe7, 0x06, 0x6f, 0x8e, 0xc4, 0x14, 0xcb, 0x62,
	0x1a, 0xd7, 0x82, 0xe4, 0x9a, 0x2b, 0xc9, 0xd8, 0x9c, 0xca, 0x6c, 0xa9, 0x0c, 0x99, 0xa5, 0xa7,
	0xbb, 0xf7, 0x3f, 0xdf, 0x6b, 0xb2, 0xe0, 0xcb, 0x4e, 0xc3, 0x38, 0x72, 0xdb, 0xa6, 0xbc, 0x76,
	0xcd, 0x62, 0xd1, 0xc2, 0x63, 0xdc, 0x6c, 0x52, 0x47, 0x7a, 0x34, 0x9b, 0xae, 0x99, 0xf0, 0xef,
	0xf2, 0x6e, 0x7f, 0xd7, 0x98, 0x94, 0x86, 0x9b, 0xcf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x0a,
	0x84, 0x1c, 0x86, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimeSeriesClient is the client API for TimeSeries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeSeriesClient interface {
	// Gets value for a time series bin.
	GetTimeSeriesBin(ctx context.Context, in *GetTimeSeriesBinRequest, opts ...grpc.CallOption) (*TimeSeriesBin, error)
	// Gets a number of time series feature values.
	GetTimeSeriesBinBulk(ctx context.Context, in *GetTimeSeriesBinBulkRequest, opts ...grpc.CallOption) (*GetTimeSeriesBinBulkResponse, error)
	// Gets average feature values for a time period.
	GetTimeSeriesAverageBulk(ctx context.Context, in *GetTimeSeriesAverageBulkRequest, opts ...grpc.CallOption) (*GetTimeSeriesBinBulkResponse, error)
	// Lists features.
	ListTimeSeriesFeatures(ctx context.Context, in *ListTimeSeriesFeaturesRequest, opts ...grpc.CallOption) (*ListTimeSeriesFeaturesResponse, error)
	// Sets a time series feature value.
	SetTimeSeriesBin(ctx context.Context, in *SetTimeSeriesBinRequest, opts ...grpc.CallOption) (*TimeSeriesBin, error)
	// Sets a time series feature.
	SetTimeSeriesFeature(ctx context.Context, in *SetTimeSeriesFeatureRequest, opts ...grpc.CallOption) (*TimeSeriesFeature, error)
	// Sets multiple time series averages
	SetTimeSeriesAverageBulk(ctx context.Context, in *SetTimeSeriesAverageBulkRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Deletes a time series bin.
	DeleteTimeSeriesBin(ctx context.Context, in *DeleteTimeSeriesBinRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteTimeSeriesFeature(ctx context.Context, in *DeleteTimeSeriesFeatureRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type timeSeriesClient struct {
	cc *grpc.ClientConn
}

func NewTimeSeriesClient(cc *grpc.ClientConn) TimeSeriesClient {
	return &timeSeriesClient{cc}
}

func (c *timeSeriesClient) GetTimeSeriesBin(ctx context.Context, in *GetTimeSeriesBinRequest, opts ...grpc.CallOption) (*TimeSeriesBin, error) {
	out := new(TimeSeriesBin)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/GetTimeSeriesBin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) GetTimeSeriesBinBulk(ctx context.Context, in *GetTimeSeriesBinBulkRequest, opts ...grpc.CallOption) (*GetTimeSeriesBinBulkResponse, error) {
	out := new(GetTimeSeriesBinBulkResponse)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/GetTimeSeriesBinBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) GetTimeSeriesAverageBulk(ctx context.Context, in *GetTimeSeriesAverageBulkRequest, opts ...grpc.CallOption) (*GetTimeSeriesBinBulkResponse, error) {
	out := new(GetTimeSeriesBinBulkResponse)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/GetTimeSeriesAverageBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) ListTimeSeriesFeatures(ctx context.Context, in *ListTimeSeriesFeaturesRequest, opts ...grpc.CallOption) (*ListTimeSeriesFeaturesResponse, error) {
	out := new(ListTimeSeriesFeaturesResponse)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/ListTimeSeriesFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) SetTimeSeriesBin(ctx context.Context, in *SetTimeSeriesBinRequest, opts ...grpc.CallOption) (*TimeSeriesBin, error) {
	out := new(TimeSeriesBin)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/SetTimeSeriesBin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) SetTimeSeriesFeature(ctx context.Context, in *SetTimeSeriesFeatureRequest, opts ...grpc.CallOption) (*TimeSeriesFeature, error) {
	out := new(TimeSeriesFeature)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/SetTimeSeriesFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) SetTimeSeriesAverageBulk(ctx context.Context, in *SetTimeSeriesAverageBulkRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/SetTimeSeriesAverageBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) DeleteTimeSeriesBin(ctx context.Context, in *DeleteTimeSeriesBinRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/DeleteTimeSeriesBin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesClient) DeleteTimeSeriesFeature(ctx context.Context, in *DeleteTimeSeriesFeatureRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.timeseries.v1.TimeSeries/DeleteTimeSeriesFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeSeriesServer is the server API for TimeSeries service.
type TimeSeriesServer interface {
	// Gets value for a time series bin.
	GetTimeSeriesBin(context.Context, *GetTimeSeriesBinRequest) (*TimeSeriesBin, error)
	// Gets a number of time series feature values.
	GetTimeSeriesBinBulk(context.Context, *GetTimeSeriesBinBulkRequest) (*GetTimeSeriesBinBulkResponse, error)
	// Gets average feature values for a time period.
	GetTimeSeriesAverageBulk(context.Context, *GetTimeSeriesAverageBulkRequest) (*GetTimeSeriesBinBulkResponse, error)
	// Lists features.
	ListTimeSeriesFeatures(context.Context, *ListTimeSeriesFeaturesRequest) (*ListTimeSeriesFeaturesResponse, error)
	// Sets a time series feature value.
	SetTimeSeriesBin(context.Context, *SetTimeSeriesBinRequest) (*TimeSeriesBin, error)
	// Sets a time series feature.
	SetTimeSeriesFeature(context.Context, *SetTimeSeriesFeatureRequest) (*TimeSeriesFeature, error)
	// Sets multiple time series averages
	SetTimeSeriesAverageBulk(context.Context, *SetTimeSeriesAverageBulkRequest) (*empty.Empty, error)
	// Deletes a time series bin.
	DeleteTimeSeriesBin(context.Context, *DeleteTimeSeriesBinRequest) (*empty.Empty, error)
	DeleteTimeSeriesFeature(context.Context, *DeleteTimeSeriesFeatureRequest) (*empty.Empty, error)
}

// UnimplementedTimeSeriesServer can be embedded to have forward compatible implementations.
type UnimplementedTimeSeriesServer struct {
}

func (*UnimplementedTimeSeriesServer) GetTimeSeriesBin(ctx context.Context, req *GetTimeSeriesBinRequest) (*TimeSeriesBin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeSeriesBin not implemented")
}
func (*UnimplementedTimeSeriesServer) GetTimeSeriesBinBulk(ctx context.Context, req *GetTimeSeriesBinBulkRequest) (*GetTimeSeriesBinBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeSeriesBinBulk not implemented")
}
func (*UnimplementedTimeSeriesServer) GetTimeSeriesAverageBulk(ctx context.Context, req *GetTimeSeriesAverageBulkRequest) (*GetTimeSeriesBinBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeSeriesAverageBulk not implemented")
}
func (*UnimplementedTimeSeriesServer) ListTimeSeriesFeatures(ctx context.Context, req *ListTimeSeriesFeaturesRequest) (*ListTimeSeriesFeaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTimeSeriesFeatures not implemented")
}
func (*UnimplementedTimeSeriesServer) SetTimeSeriesBin(ctx context.Context, req *SetTimeSeriesBinRequest) (*TimeSeriesBin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimeSeriesBin not implemented")
}
func (*UnimplementedTimeSeriesServer) SetTimeSeriesFeature(ctx context.Context, req *SetTimeSeriesFeatureRequest) (*TimeSeriesFeature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimeSeriesFeature not implemented")
}
func (*UnimplementedTimeSeriesServer) SetTimeSeriesAverageBulk(ctx context.Context, req *SetTimeSeriesAverageBulkRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimeSeriesAverageBulk not implemented")
}
func (*UnimplementedTimeSeriesServer) DeleteTimeSeriesBin(ctx context.Context, req *DeleteTimeSeriesBinRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTimeSeriesBin not implemented")
}
func (*UnimplementedTimeSeriesServer) DeleteTimeSeriesFeature(ctx context.Context, req *DeleteTimeSeriesFeatureRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTimeSeriesFeature not implemented")
}

func RegisterTimeSeriesServer(s *grpc.Server, srv TimeSeriesServer) {
	s.RegisterService(&_TimeSeries_serviceDesc, srv)
}

func _TimeSeries_GetTimeSeriesBin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeSeriesBinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).GetTimeSeriesBin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/GetTimeSeriesBin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).GetTimeSeriesBin(ctx, req.(*GetTimeSeriesBinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_GetTimeSeriesBinBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeSeriesBinBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).GetTimeSeriesBinBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/GetTimeSeriesBinBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).GetTimeSeriesBinBulk(ctx, req.(*GetTimeSeriesBinBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_GetTimeSeriesAverageBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeSeriesAverageBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).GetTimeSeriesAverageBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/GetTimeSeriesAverageBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).GetTimeSeriesAverageBulk(ctx, req.(*GetTimeSeriesAverageBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_ListTimeSeriesFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTimeSeriesFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).ListTimeSeriesFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/ListTimeSeriesFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).ListTimeSeriesFeatures(ctx, req.(*ListTimeSeriesFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_SetTimeSeriesBin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimeSeriesBinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).SetTimeSeriesBin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/SetTimeSeriesBin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).SetTimeSeriesBin(ctx, req.(*SetTimeSeriesBinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_SetTimeSeriesFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimeSeriesFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).SetTimeSeriesFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/SetTimeSeriesFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).SetTimeSeriesFeature(ctx, req.(*SetTimeSeriesFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_SetTimeSeriesAverageBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimeSeriesAverageBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).SetTimeSeriesAverageBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/SetTimeSeriesAverageBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).SetTimeSeriesAverageBulk(ctx, req.(*SetTimeSeriesAverageBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_DeleteTimeSeriesBin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTimeSeriesBinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).DeleteTimeSeriesBin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/DeleteTimeSeriesBin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).DeleteTimeSeriesBin(ctx, req.(*DeleteTimeSeriesBinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeries_DeleteTimeSeriesFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTimeSeriesFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServer).DeleteTimeSeriesFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.timeseries.v1.TimeSeries/DeleteTimeSeriesFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServer).DeleteTimeSeriesFeature(ctx, req.(*DeleteTimeSeriesFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeSeries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topos.timeseries.v1.TimeSeries",
	HandlerType: (*TimeSeriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeSeriesBin",
			Handler:    _TimeSeries_GetTimeSeriesBin_Handler,
		},
		{
			MethodName: "GetTimeSeriesBinBulk",
			Handler:    _TimeSeries_GetTimeSeriesBinBulk_Handler,
		},
		{
			MethodName: "GetTimeSeriesAverageBulk",
			Handler:    _TimeSeries_GetTimeSeriesAverageBulk_Handler,
		},
		{
			MethodName: "ListTimeSeriesFeatures",
			Handler:    _TimeSeries_ListTimeSeriesFeatures_Handler,
		},
		{
			MethodName: "SetTimeSeriesBin",
			Handler:    _TimeSeries_SetTimeSeriesBin_Handler,
		},
		{
			MethodName: "SetTimeSeriesFeature",
			Handler:    _TimeSeries_SetTimeSeriesFeature_Handler,
		},
		{
			MethodName: "SetTimeSeriesAverageBulk",
			Handler:    _TimeSeries_SetTimeSeriesAverageBulk_Handler,
		},
		{
			MethodName: "DeleteTimeSeriesBin",
			Handler:    _TimeSeries_DeleteTimeSeriesBin_Handler,
		},
		{
			MethodName: "DeleteTimeSeriesFeature",
			Handler:    _TimeSeries_DeleteTimeSeriesFeature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topos/timeseries/v1/time-series.proto",
}
