type: google.api.Service
config_version: 3
name: v1.topiary.endpoints.topos.com

title: Topos Topiary API
apis:
 - name: topos.topiary.v1.Topiary

authentication:
  providers:
  - id: auth0_jwk
    issuer: https://auth.topos.com/
    jwks_uri: https://auth.topos.com/.well-known/jwks.json
    audiences: endpoints.topos.com
  rules:
  - selector: "*"
    requirements:
      - provider_id: auth0_jwk

usage:
  rules:
    - selector: "topos.topiary.v1.*"
      allow_unregistered_calls: true
