// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topos/ontology/v1/ontology.proto

package ontology

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FeatureStats struct {
	Min                  float64  `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Average              float64  `protobuf:"fixed64,3,opt,name=average,proto3" json:"average,omitempty"`
	Median               float64  `protobuf:"fixed64,4,opt,name=median,proto3" json:"median,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureStats) Reset()         { *m = FeatureStats{} }
func (m *FeatureStats) String() string { return proto.CompactTextString(m) }
func (*FeatureStats) ProtoMessage()    {}
func (*FeatureStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{0}
}

func (m *FeatureStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats.Unmarshal(m, b)
}
func (m *FeatureStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats.Marshal(b, m, deterministic)
}
func (m *FeatureStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats.Merge(m, src)
}
func (m *FeatureStats) XXX_Size() int {
	return xxx_messageInfo_FeatureStats.Size(m)
}
func (m *FeatureStats) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats proto.InternalMessageInfo

func (m *FeatureStats) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *FeatureStats) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *FeatureStats) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *FeatureStats) GetMedian() float64 {
	if m != nil {
		return m.Median
	}
	return 0
}

type Contact struct {
	// The full name of the contact.
	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// The title of the contact.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The phonenumber of the contact.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The phone number of the contact.
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// The regions that a contact covers
	Regions              []string `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{1}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Contact) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Contact) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

type Brand struct {
	// The name of the point brand. It must have the format `"brands/{brand}"`.
	// `{brand}` must match the [regular
	// expression](https://github.com/google/re2/wiki/Syntax)
	// `^[a-z\d]+(-[a-z\d]+)*$`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The display name of the brand.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The formatted, single-line address of the brand's headquarters.
	FormattedAddress string `protobuf:"bytes,3,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	// The email of the brand.
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// The realestate email of the brand.
	RealestateEmail string `protobuf:"bytes,5,opt,name=realestate_email,json=realestateEmail,proto3" json:"realestate_email,omitempty"`
	// The phone number of the brand.
	PhoneNumber string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// The contacts for the brand.
	Contacts []*Contact `protobuf:"bytes,7,rep,name=contacts,proto3" json:"contacts,omitempty"`
	// The [2017 NAICS
	// code](https://www.census.gov/cgi-bin/sssd/naics/naicsrch?chart=2017) of the
	// brand.
	Naics string `protobuf:"bytes,8,opt,name=naics,proto3" json:"naics,omitempty"`
	// The postal code of the brand's headquarters.
	PostalCode string `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// The feature set statistics for this brand's locations.
	FeatureSetFeatureStats map[string]*FeatureStats `protobuf:"bytes,10,rep,name=feature_set_feature_stats,json=featureSetFeatureStats,proto3" json:"feature_set_feature_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The brand's location preferences by region.
	RegionPreferences map[string]*Brand_Preferences `protobuf:"bytes,11,rep,name=region_preferences,json=regionPreferences,proto3" json:"region_preferences,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// A list of brand tags.
	Tags []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// Exclude the brand from results.
	Exclude bool `protobuf:"varint,13,opt,name=exclude,proto3" json:"exclude,omitempty"`
	// The creation timestamp of the brand.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of an brand.
	UpdateTime        *timestamp.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	TotalLocations    int64                `protobuf:"varint,16,opt,name=total_locations,json=totalLocations,proto3" json:"total_locations,omitempty"`
	StatesOfExpansion []string             `protobuf:"bytes,17,rep,name=states_of_expansion,json=statesOfExpansion,proto3" json:"states_of_expansion,omitempty"`
	StatesOfOperation []string             `protobuf:"bytes,18,rep,name=states_of_operation,json=statesOfOperation,proto3" json:"states_of_operation,omitempty"`
	Website           string               `protobuf:"bytes,19,opt,name=website,proto3" json:"website,omitempty"`
	// The name of a parent brand, if existing
	ParentName string `protobuf:"bytes,20,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	// Preferred cotenants for a particular brand
	PreferredCotenants []string `protobuf:"bytes,21,rep,name=preferred_cotenants,json=preferredCotenants,proto3" json:"preferred_cotenants,omitempty"`
	// Preferred road types for a brand
	PreferredRoadType []int64 `protobuf:"varint,22,rep,packed,name=preferred_road_type,json=preferredRoadType,proto3" json:"preferred_road_type,omitempty"`
	// Preferred location type for a brand
	LocationTypesConsidered []string `protobuf:"bytes,23,rep,name=location_types_considered,json=locationTypesConsidered,proto3" json:"location_types_considered,omitempty"`
	// Pricepoint for a brand
	Pricing string `protobuf:"bytes,24,opt,name=pricing,proto3" json:"pricing,omitempty"`
	// "Vibes" of a brand
	Attributes []string `protobuf:"bytes,25,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// description of a brand
	Description string `protobuf:"bytes,26,opt,name=description,proto3" json:"description,omitempty"`
	// neighborhood correlations for a brand
	NeighborhoodCorrelations []string `protobuf:"bytes,27,rep,name=neighborhood_correlations,json=neighborhoodCorrelations,proto3" json:"neighborhood_correlations,omitempty"`
	// the minimum distance in meters to another brand location
	MinimumDistance int64 `protobuf:"varint,28,opt,name=minimum_distance,json=minimumDistance,proto3" json:"minimum_distance,omitempty"`
	// the approximate size of a brand - large, medium, small, etc.
	BrandSize string `protobuf:"bytes,29,opt,name=brand_size,json=brandSize,proto3" json:"brand_size,omitempty"`
	// the income bracket a brand targets - high, low, etc
	IncomeIqr string `protobuf:"bytes,30,opt,name=income_iqr,json=incomeIqr,proto3" json:"income_iqr,omitempty"`
	// the count of contacts for a brand
	ContactCount         string   `protobuf:"bytes,31,opt,name=contact_count,json=contactCount,proto3" json:"contact_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand) Reset()         { *m = Brand{} }
func (m *Brand) String() string { return proto.CompactTextString(m) }
func (*Brand) ProtoMessage()    {}
func (*Brand) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{2}
}

func (m *Brand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand.Unmarshal(m, b)
}
func (m *Brand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand.Marshal(b, m, deterministic)
}
func (m *Brand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand.Merge(m, src)
}
func (m *Brand) XXX_Size() int {
	return xxx_messageInfo_Brand.Size(m)
}
func (m *Brand) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand.DiscardUnknown(m)
}

var xxx_messageInfo_Brand proto.InternalMessageInfo

func (m *Brand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Brand) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Brand) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Brand) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Brand) GetRealestateEmail() string {
	if m != nil {
		return m.RealestateEmail
	}
	return ""
}

func (m *Brand) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Brand) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Brand) GetNaics() string {
	if m != nil {
		return m.Naics
	}
	return ""
}

func (m *Brand) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Brand) GetFeatureSetFeatureStats() map[string]*FeatureStats {
	if m != nil {
		return m.FeatureSetFeatureStats
	}
	return nil
}

func (m *Brand) GetRegionPreferences() map[string]*Brand_Preferences {
	if m != nil {
		return m.RegionPreferences
	}
	return nil
}

func (m *Brand) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Brand) GetExclude() bool {
	if m != nil {
		return m.Exclude
	}
	return false
}

func (m *Brand) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Brand) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Brand) GetTotalLocations() int64 {
	if m != nil {
		return m.TotalLocations
	}
	return 0
}

func (m *Brand) GetStatesOfExpansion() []string {
	if m != nil {
		return m.StatesOfExpansion
	}
	return nil
}

func (m *Brand) GetStatesOfOperation() []string {
	if m != nil {
		return m.StatesOfOperation
	}
	return nil
}

func (m *Brand) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Brand) GetParentName() string {
	if m != nil {
		return m.ParentName
	}
	return ""
}

func (m *Brand) GetPreferredCotenants() []string {
	if m != nil {
		return m.PreferredCotenants
	}
	return nil
}

func (m *Brand) GetPreferredRoadType() []int64 {
	if m != nil {
		return m.PreferredRoadType
	}
	return nil
}

func (m *Brand) GetLocationTypesConsidered() []string {
	if m != nil {
		return m.LocationTypesConsidered
	}
	return nil
}

func (m *Brand) GetPricing() string {
	if m != nil {
		return m.Pricing
	}
	return ""
}

func (m *Brand) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Brand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Brand) GetNeighborhoodCorrelations() []string {
	if m != nil {
		return m.NeighborhoodCorrelations
	}
	return nil
}

func (m *Brand) GetMinimumDistance() int64 {
	if m != nil {
		return m.MinimumDistance
	}
	return 0
}

func (m *Brand) GetBrandSize() string {
	if m != nil {
		return m.BrandSize
	}
	return ""
}

func (m *Brand) GetIncomeIqr() string {
	if m != nil {
		return m.IncomeIqr
	}
	return ""
}

func (m *Brand) GetContactCount() string {
	if m != nil {
		return m.ContactCount
	}
	return ""
}

type Brand_Preferences struct {
	// The prefered square footage of the brand.
	PreferredGla string `protobuf:"bytes,1,opt,name=preferred_gla,json=preferredGla,proto3" json:"preferred_gla,omitempty"`
	// The percentage of locations where this brand shares a building.
	Inline float64 `protobuf:"fixed64,2,opt,name=inline,proto3" json:"inline,omitempty"`
	// The percentage of locations where this brand occupies a stand-alone
	// building.
	StandAlone           float64  `protobuf:"fixed64,3,opt,name=stand_alone,json=standAlone,proto3" json:"stand_alone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand_Preferences) Reset()         { *m = Brand_Preferences{} }
func (m *Brand_Preferences) String() string { return proto.CompactTextString(m) }
func (*Brand_Preferences) ProtoMessage()    {}
func (*Brand_Preferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{2, 1}
}

func (m *Brand_Preferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand_Preferences.Unmarshal(m, b)
}
func (m *Brand_Preferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand_Preferences.Marshal(b, m, deterministic)
}
func (m *Brand_Preferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand_Preferences.Merge(m, src)
}
func (m *Brand_Preferences) XXX_Size() int {
	return xxx_messageInfo_Brand_Preferences.Size(m)
}
func (m *Brand_Preferences) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand_Preferences.DiscardUnknown(m)
}

var xxx_messageInfo_Brand_Preferences proto.InternalMessageInfo

func (m *Brand_Preferences) GetPreferredGla() string {
	if m != nil {
		return m.PreferredGla
	}
	return ""
}

func (m *Brand_Preferences) GetInline() float64 {
	if m != nil {
		return m.Inline
	}
	return 0
}

func (m *Brand_Preferences) GetStandAlone() float64 {
	if m != nil {
		return m.StandAlone
	}
	return 0
}

type Tag struct {
	// The name of the tag. It must have the format `"tags/{tag}"`. `{tag}`
	// must match the [regular
	// expression](https://github.com/google/re2/wiki/Syntax)
	// `^[a-z\d]+(-[a-z\d]+)*$`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The display name of the tag.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Exclude tag from results.
	Exclude bool `protobuf:"varint,3,opt,name=exclude,proto3" json:"exclude,omitempty"`
	// The plural display name of the tag.
	PluralDisplayName string `protobuf:"bytes,4,opt,name=plural_display_name,json=pluralDisplayName,proto3" json:"plural_display_name,omitempty"`
	// The names of a parent tags, if existing
	ParentName           []string `protobuf:"bytes,5,rep,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{3}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Tag) GetExclude() bool {
	if m != nil {
		return m.Exclude
	}
	return false
}

func (m *Tag) GetPluralDisplayName() string {
	if m != nil {
		return m.PluralDisplayName
	}
	return ""
}

func (m *Tag) GetParentName() []string {
	if m != nil {
		return m.ParentName
	}
	return nil
}

type GetBrandRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandRequest) Reset()         { *m = GetBrandRequest{} }
func (m *GetBrandRequest) String() string { return proto.CompactTextString(m) }
func (*GetBrandRequest) ProtoMessage()    {}
func (*GetBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{4}
}

func (m *GetBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandRequest.Unmarshal(m, b)
}
func (m *GetBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandRequest.Marshal(b, m, deterministic)
}
func (m *GetBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandRequest.Merge(m, src)
}
func (m *GetBrandRequest) XXX_Size() int {
	return xxx_messageInfo_GetBrandRequest.Size(m)
}
func (m *GetBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandRequest proto.InternalMessageInfo

func (m *GetBrandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBrandFeaturesRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandFeaturesRequest) Reset()         { *m = GetBrandFeaturesRequest{} }
func (m *GetBrandFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*GetBrandFeaturesRequest) ProtoMessage()    {}
func (*GetBrandFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{5}
}

func (m *GetBrandFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandFeaturesRequest.Unmarshal(m, b)
}
func (m *GetBrandFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandFeaturesRequest.Marshal(b, m, deterministic)
}
func (m *GetBrandFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandFeaturesRequest.Merge(m, src)
}
func (m *GetBrandFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_GetBrandFeaturesRequest.Size(m)
}
func (m *GetBrandFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandFeaturesRequest proto.InternalMessageInfo

func (m *GetBrandFeaturesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBrandsMinDistanceRequest struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandsMinDistanceRequest) Reset()         { *m = GetBrandsMinDistanceRequest{} }
func (m *GetBrandsMinDistanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBrandsMinDistanceRequest) ProtoMessage()    {}
func (*GetBrandsMinDistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{6}
}

func (m *GetBrandsMinDistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandsMinDistanceRequest.Unmarshal(m, b)
}
func (m *GetBrandsMinDistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandsMinDistanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBrandsMinDistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandsMinDistanceRequest.Merge(m, src)
}
func (m *GetBrandsMinDistanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBrandsMinDistanceRequest.Size(m)
}
func (m *GetBrandsMinDistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandsMinDistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandsMinDistanceRequest proto.InternalMessageInfo

func (m *GetBrandsMinDistanceRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type GetBrandContactsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandContactsRequest) Reset()         { *m = GetBrandContactsRequest{} }
func (m *GetBrandContactsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBrandContactsRequest) ProtoMessage()    {}
func (*GetBrandContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{7}
}

func (m *GetBrandContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandContactsRequest.Unmarshal(m, b)
}
func (m *GetBrandContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandContactsRequest.Marshal(b, m, deterministic)
}
func (m *GetBrandContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandContactsRequest.Merge(m, src)
}
func (m *GetBrandContactsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBrandContactsRequest.Size(m)
}
func (m *GetBrandContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandContactsRequest proto.InternalMessageInfo

func (m *GetBrandContactsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBrandsBulkRequest struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandsBulkRequest) Reset()         { *m = GetBrandsBulkRequest{} }
func (m *GetBrandsBulkRequest) String() string { return proto.CompactTextString(m) }
func (*GetBrandsBulkRequest) ProtoMessage()    {}
func (*GetBrandsBulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{8}
}

func (m *GetBrandsBulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandsBulkRequest.Unmarshal(m, b)
}
func (m *GetBrandsBulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandsBulkRequest.Marshal(b, m, deterministic)
}
func (m *GetBrandsBulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandsBulkRequest.Merge(m, src)
}
func (m *GetBrandsBulkRequest) XXX_Size() int {
	return xxx_messageInfo_GetBrandsBulkRequest.Size(m)
}
func (m *GetBrandsBulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandsBulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandsBulkRequest proto.InternalMessageInfo

func (m *GetBrandsBulkRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type SearchBrandsRequest struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	PreferredGla         []int32  `protobuf:"varint,3,rep,packed,name=preferred_gla,json=preferredGla,proto3" json:"preferred_gla,omitempty"`
	TenancyPrefs         []string `protobuf:"bytes,4,rep,name=tenancy_prefs,json=tenancyPrefs,proto3" json:"tenancy_prefs,omitempty"`
	RegionsOfExpansion   []string `protobuf:"bytes,5,rep,name=regions_of_expansion,json=regionsOfExpansion,proto3" json:"regions_of_expansion,omitempty"`
	RegionsOfOperation   []string `protobuf:"bytes,6,rep,name=regions_of_operation,json=regionsOfOperation,proto3" json:"regions_of_operation,omitempty"`
	Attributes           []string `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty"`
	IncomeIqr            string   `protobuf:"bytes,8,opt,name=income_iqr,json=incomeIqr,proto3" json:"income_iqr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBrandsRequest) Reset()         { *m = SearchBrandsRequest{} }
func (m *SearchBrandsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBrandsRequest) ProtoMessage()    {}
func (*SearchBrandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{9}
}

func (m *SearchBrandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBrandsRequest.Unmarshal(m, b)
}
func (m *SearchBrandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBrandsRequest.Marshal(b, m, deterministic)
}
func (m *SearchBrandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBrandsRequest.Merge(m, src)
}
func (m *SearchBrandsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBrandsRequest.Size(m)
}
func (m *SearchBrandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBrandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBrandsRequest proto.InternalMessageInfo

func (m *SearchBrandsRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SearchBrandsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SearchBrandsRequest) GetPreferredGla() []int32 {
	if m != nil {
		return m.PreferredGla
	}
	return nil
}

func (m *SearchBrandsRequest) GetTenancyPrefs() []string {
	if m != nil {
		return m.TenancyPrefs
	}
	return nil
}

func (m *SearchBrandsRequest) GetRegionsOfExpansion() []string {
	if m != nil {
		return m.RegionsOfExpansion
	}
	return nil
}

func (m *SearchBrandsRequest) GetRegionsOfOperation() []string {
	if m != nil {
		return m.RegionsOfOperation
	}
	return nil
}

func (m *SearchBrandsRequest) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *SearchBrandsRequest) GetIncomeIqr() string {
	if m != nil {
		return m.IncomeIqr
	}
	return ""
}

type ListBrandsRequest struct {
	// The maximum number of items to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBrandsRequest) Reset()         { *m = ListBrandsRequest{} }
func (m *ListBrandsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBrandsRequest) ProtoMessage()    {}
func (*ListBrandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{10}
}

func (m *ListBrandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBrandsRequest.Unmarshal(m, b)
}
func (m *ListBrandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBrandsRequest.Marshal(b, m, deterministic)
}
func (m *ListBrandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBrandsRequest.Merge(m, src)
}
func (m *ListBrandsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBrandsRequest.Size(m)
}
func (m *ListBrandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBrandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBrandsRequest proto.InternalMessageInfo

func (m *ListBrandsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListBrandsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListBrandsResponse struct {
	Brands []*Brand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more
	// results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBrandsResponse) Reset()         { *m = ListBrandsResponse{} }
func (m *ListBrandsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBrandsResponse) ProtoMessage()    {}
func (*ListBrandsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{11}
}

func (m *ListBrandsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBrandsResponse.Unmarshal(m, b)
}
func (m *ListBrandsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBrandsResponse.Marshal(b, m, deterministic)
}
func (m *ListBrandsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBrandsResponse.Merge(m, src)
}
func (m *ListBrandsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBrandsResponse.Size(m)
}
func (m *ListBrandsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBrandsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBrandsResponse proto.InternalMessageInfo

func (m *ListBrandsResponse) GetBrands() []*Brand {
	if m != nil {
		return m.Brands
	}
	return nil
}

func (m *ListBrandsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type SetBrandRequest struct {
	Brand                *Brand   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBrandRequest) Reset()         { *m = SetBrandRequest{} }
func (m *SetBrandRequest) String() string { return proto.CompactTextString(m) }
func (*SetBrandRequest) ProtoMessage()    {}
func (*SetBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{12}
}

func (m *SetBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBrandRequest.Unmarshal(m, b)
}
func (m *SetBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBrandRequest.Marshal(b, m, deterministic)
}
func (m *SetBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBrandRequest.Merge(m, src)
}
func (m *SetBrandRequest) XXX_Size() int {
	return xxx_messageInfo_SetBrandRequest.Size(m)
}
func (m *SetBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBrandRequest proto.InternalMessageInfo

func (m *SetBrandRequest) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

type DeleteBrandRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBrandRequest) Reset()         { *m = DeleteBrandRequest{} }
func (m *DeleteBrandRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBrandRequest) ProtoMessage()    {}
func (*DeleteBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{13}
}

func (m *DeleteBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBrandRequest.Unmarshal(m, b)
}
func (m *DeleteBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBrandRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBrandRequest.Merge(m, src)
}
func (m *DeleteBrandRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBrandRequest.Size(m)
}
func (m *DeleteBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBrandRequest proto.InternalMessageInfo

func (m *DeleteBrandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTagRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagRequest) Reset()         { *m = GetTagRequest{} }
func (m *GetTagRequest) String() string { return proto.CompactTextString(m) }
func (*GetTagRequest) ProtoMessage()    {}
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{14}
}

func (m *GetTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagRequest.Unmarshal(m, b)
}
func (m *GetTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagRequest.Marshal(b, m, deterministic)
}
func (m *GetTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagRequest.Merge(m, src)
}
func (m *GetTagRequest) XXX_Size() int {
	return xxx_messageInfo_GetTagRequest.Size(m)
}
func (m *GetTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagRequest proto.InternalMessageInfo

func (m *GetTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetTagRequest struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTagRequest) Reset()         { *m = SetTagRequest{} }
func (m *SetTagRequest) String() string { return proto.CompactTextString(m) }
func (*SetTagRequest) ProtoMessage()    {}
func (*SetTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{15}
}

func (m *SetTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTagRequest.Unmarshal(m, b)
}
func (m *SetTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTagRequest.Marshal(b, m, deterministic)
}
func (m *SetTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTagRequest.Merge(m, src)
}
func (m *SetTagRequest) XXX_Size() int {
	return xxx_messageInfo_SetTagRequest.Size(m)
}
func (m *SetTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTagRequest proto.InternalMessageInfo

func (m *SetTagRequest) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type ListTagsRequest struct {
	// The maximum number of items to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagsRequest) Reset()         { *m = ListTagsRequest{} }
func (m *ListTagsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTagsRequest) ProtoMessage()    {}
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{16}
}

func (m *ListTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagsRequest.Unmarshal(m, b)
}
func (m *ListTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagsRequest.Marshal(b, m, deterministic)
}
func (m *ListTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagsRequest.Merge(m, src)
}
func (m *ListTagsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTagsRequest.Size(m)
}
func (m *ListTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagsRequest proto.InternalMessageInfo

func (m *ListTagsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListTagsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListTagsResponse struct {
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more
	// results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagsResponse) Reset()         { *m = ListTagsResponse{} }
func (m *ListTagsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTagsResponse) ProtoMessage()    {}
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{17}
}

func (m *ListTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagsResponse.Unmarshal(m, b)
}
func (m *ListTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagsResponse.Marshal(b, m, deterministic)
}
func (m *ListTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagsResponse.Merge(m, src)
}
func (m *ListTagsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTagsResponse.Size(m)
}
func (m *ListTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagsResponse proto.InternalMessageInfo

func (m *ListTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ListTagsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type DeleteTagRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagRequest) Reset()         { *m = DeleteTagRequest{} }
func (m *DeleteTagRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagRequest) ProtoMessage()    {}
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{18}
}

func (m *DeleteTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagRequest.Unmarshal(m, b)
}
func (m *DeleteTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagRequest.Merge(m, src)
}
func (m *DeleteTagRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagRequest.Size(m)
}
func (m *DeleteTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagRequest proto.InternalMessageInfo

func (m *DeleteTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBrandFeaturesResponse struct {
	Features             map[string]*FeatureStats `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetBrandFeaturesResponse) Reset()         { *m = GetBrandFeaturesResponse{} }
func (m *GetBrandFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*GetBrandFeaturesResponse) ProtoMessage()    {}
func (*GetBrandFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{19}
}

func (m *GetBrandFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandFeaturesResponse.Unmarshal(m, b)
}
func (m *GetBrandFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandFeaturesResponse.Marshal(b, m, deterministic)
}
func (m *GetBrandFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandFeaturesResponse.Merge(m, src)
}
func (m *GetBrandFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_GetBrandFeaturesResponse.Size(m)
}
func (m *GetBrandFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandFeaturesResponse proto.InternalMessageInfo

func (m *GetBrandFeaturesResponse) GetFeatures() map[string]*FeatureStats {
	if m != nil {
		return m.Features
	}
	return nil
}

type GetBrandContactsResponse struct {
	Contacts             []*Contact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBrandContactsResponse) Reset()         { *m = GetBrandContactsResponse{} }
func (m *GetBrandContactsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBrandContactsResponse) ProtoMessage()    {}
func (*GetBrandContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{20}
}

func (m *GetBrandContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandContactsResponse.Unmarshal(m, b)
}
func (m *GetBrandContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandContactsResponse.Marshal(b, m, deterministic)
}
func (m *GetBrandContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandContactsResponse.Merge(m, src)
}
func (m *GetBrandContactsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBrandContactsResponse.Size(m)
}
func (m *GetBrandContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandContactsResponse proto.InternalMessageInfo

func (m *GetBrandContactsResponse) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type GetBrandsMinDistanceResponse struct {
	MinimumDistances     map[string]int64 `protobuf:"bytes,1,rep,name=minimum_distances,json=minimumDistances,proto3" json:"minimum_distances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetBrandsMinDistanceResponse) Reset()         { *m = GetBrandsMinDistanceResponse{} }
func (m *GetBrandsMinDistanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBrandsMinDistanceResponse) ProtoMessage()    {}
func (*GetBrandsMinDistanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{21}
}

func (m *GetBrandsMinDistanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandsMinDistanceResponse.Unmarshal(m, b)
}
func (m *GetBrandsMinDistanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandsMinDistanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBrandsMinDistanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandsMinDistanceResponse.Merge(m, src)
}
func (m *GetBrandsMinDistanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBrandsMinDistanceResponse.Size(m)
}
func (m *GetBrandsMinDistanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandsMinDistanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandsMinDistanceResponse proto.InternalMessageInfo

func (m *GetBrandsMinDistanceResponse) GetMinimumDistances() map[string]int64 {
	if m != nil {
		return m.MinimumDistances
	}
	return nil
}

type GetBrandsBulkResponse struct {
	Brands               []*Brand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBrandsBulkResponse) Reset()         { *m = GetBrandsBulkResponse{} }
func (m *GetBrandsBulkResponse) String() string { return proto.CompactTextString(m) }
func (*GetBrandsBulkResponse) ProtoMessage()    {}
func (*GetBrandsBulkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{22}
}

func (m *GetBrandsBulkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBrandsBulkResponse.Unmarshal(m, b)
}
func (m *GetBrandsBulkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBrandsBulkResponse.Marshal(b, m, deterministic)
}
func (m *GetBrandsBulkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBrandsBulkResponse.Merge(m, src)
}
func (m *GetBrandsBulkResponse) XXX_Size() int {
	return xxx_messageInfo_GetBrandsBulkResponse.Size(m)
}
func (m *GetBrandsBulkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBrandsBulkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBrandsBulkResponse proto.InternalMessageInfo

func (m *GetBrandsBulkResponse) GetBrands() []*Brand {
	if m != nil {
		return m.Brands
	}
	return nil
}

type SearchBrandsResponse struct {
	Brands               []*Brand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBrandsResponse) Reset()         { *m = SearchBrandsResponse{} }
func (m *SearchBrandsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchBrandsResponse) ProtoMessage()    {}
func (*SearchBrandsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3009b39f7ca3919e, []int{23}
}

func (m *SearchBrandsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBrandsResponse.Unmarshal(m, b)
}
func (m *SearchBrandsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBrandsResponse.Marshal(b, m, deterministic)
}
func (m *SearchBrandsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBrandsResponse.Merge(m, src)
}
func (m *SearchBrandsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchBrandsResponse.Size(m)
}
func (m *SearchBrandsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBrandsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBrandsResponse proto.InternalMessageInfo

func (m *SearchBrandsResponse) GetBrands() []*Brand {
	if m != nil {
		return m.Brands
	}
	return nil
}

func init() {
	proto.RegisterType((*FeatureStats)(nil), "topos.ontology.v1.FeatureStats")
	proto.RegisterType((*Contact)(nil), "topos.ontology.v1.Contact")
	proto.RegisterType((*Brand)(nil), "topos.ontology.v1.Brand")
	proto.RegisterMapType((map[string]*FeatureStats)(nil), "topos.ontology.v1.Brand.FeatureSetFeatureStatsEntry")
	proto.RegisterMapType((map[string]*Brand_Preferences)(nil), "topos.ontology.v1.Brand.RegionPreferencesEntry")
	proto.RegisterType((*Brand_Preferences)(nil), "topos.ontology.v1.Brand.Preferences")
	proto.RegisterType((*Tag)(nil), "topos.ontology.v1.Tag")
	proto.RegisterType((*GetBrandRequest)(nil), "topos.ontology.v1.GetBrandRequest")
	proto.RegisterType((*GetBrandFeaturesRequest)(nil), "topos.ontology.v1.GetBrandFeaturesRequest")
	proto.RegisterType((*GetBrandsMinDistanceRequest)(nil), "topos.ontology.v1.GetBrandsMinDistanceRequest")
	proto.RegisterType((*GetBrandContactsRequest)(nil), "topos.ontology.v1.GetBrandContactsRequest")
	proto.RegisterType((*GetBrandsBulkRequest)(nil), "topos.ontology.v1.GetBrandsBulkRequest")
	proto.RegisterType((*SearchBrandsRequest)(nil), "topos.ontology.v1.SearchBrandsRequest")
	proto.RegisterType((*ListBrandsRequest)(nil), "topos.ontology.v1.ListBrandsRequest")
	proto.RegisterType((*ListBrandsResponse)(nil), "topos.ontology.v1.ListBrandsResponse")
	proto.RegisterType((*SetBrandRequest)(nil), "topos.ontology.v1.SetBrandRequest")
	proto.RegisterType((*DeleteBrandRequest)(nil), "topos.ontology.v1.DeleteBrandRequest")
	proto.RegisterType((*GetTagRequest)(nil), "topos.ontology.v1.GetTagRequest")
	proto.RegisterType((*SetTagRequest)(nil), "topos.ontology.v1.SetTagRequest")
	proto.RegisterType((*ListTagsRequest)(nil), "topos.ontology.v1.ListTagsRequest")
	proto.RegisterType((*ListTagsResponse)(nil), "topos.ontology.v1.ListTagsResponse")
	proto.RegisterType((*DeleteTagRequest)(nil), "topos.ontology.v1.DeleteTagRequest")
	proto.RegisterType((*GetBrandFeaturesResponse)(nil), "topos.ontology.v1.GetBrandFeaturesResponse")
	proto.RegisterMapType((map[string]*FeatureStats)(nil), "topos.ontology.v1.GetBrandFeaturesResponse.FeaturesEntry")
	proto.RegisterType((*GetBrandContactsResponse)(nil), "topos.ontology.v1.GetBrandContactsResponse")
	proto.RegisterType((*GetBrandsMinDistanceResponse)(nil), "topos.ontology.v1.GetBrandsMinDistanceResponse")
	proto.RegisterMapType((map[string]int64)(nil), "topos.ontology.v1.GetBrandsMinDistanceResponse.MinimumDistancesEntry")
	proto.RegisterType((*GetBrandsBulkResponse)(nil), "topos.ontology.v1.GetBrandsBulkResponse")
	proto.RegisterType((*SearchBrandsResponse)(nil), "topos.ontology.v1.SearchBrandsResponse")
}

func init() { proto.RegisterFile("topos/ontology/v1/ontology.proto", fileDescriptor_3009b39f7ca3919e) }

var fileDescriptor_3009b39f7ca3919e = []byte{
	// 1879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4f, 0x73, 0xdb, 0xc6,
	0x15, 0x1f, 0x9a, 0x96, 0x4c, 0x3e, 0x4a, 0x91, 0xb8, 0x92, 0x65, 0x88, 0x92, 0x6d, 0x16, 0x4a,
	0x64, 0x56, 0x89, 0xc9, 0xd8, 0x69, 0x3b, 0x8d, 0x3c, 0x3d, 0xd8, 0xb2, 0xea, 0x66, 0x26, 0x8e,
	0x33, 0x90, 0x7a, 0xe9, 0xb4, 0xc5, 0xac, 0x80, 0x15, 0x04, 0x0b, 0xc0, 0xc2, 0xd8, 0xa5, 0x2a,
	0xa5, 0x93, 0x1e, 0x3a, 0xbd, 0x77, 0x3a, 0xfd, 0x00, 0x3d, 0xf4, 0xd0, 0xcf, 0xd0, 0x4f, 0xd1,
	0x43, 0x0f, 0xfd, 0x02, 0xfd, 0x20, 0x99, 0x7d, 0xbb, 0x20, 0x01, 0x12, 0xa4, 0x14, 0x4f, 0x6e,
	0xd8, 0xb7, 0x6f, 0xdf, 0xef, 0xfd, 0x7f, 0x6f, 0x00, 0x5d, 0xc9, 0x53, 0x2e, 0x06, 0x3c, 0x91,
	0x3c, 0xe2, 0xc1, 0xd5, 0xe0, 0xe2, 0xc9, 0xe8, 0xbb, 0x9f, 0x66, 0x5c, 0x72, 0xd2, 0x46, 0x8e,
	0xfe, 0x88, 0x7a, 0xf1, 0xa4, 0xb3, 0x1d, 0x70, 0x1e, 0x44, 0x6c, 0x40, 0xd3, 0x70, 0x40, 0x93,
	0x84, 0x4b, 0x2a, 0x43, 0x9e, 0x08, 0xfd, 0xa0, 0xb3, 0x65, 0x6e, 0xf1, 0x74, 0x32, 0x3c, 0x1d,
	0xb0, 0x38, 0x95, 0x46, 0x5a, 0xe7, 0xe1, 0xe4, 0xa5, 0x0c, 0x63, 0x26, 0x24, 0x8d, 0x53, 0xcd,
	0x60, 0xfb, 0xb0, 0xf4, 0x4b, 0x46, 0xe5, 0x30, 0x63, 0x47, 0x92, 0x4a, 0x41, 0x56, 0xa1, 0x1e,
	0x87, 0x89, 0x55, 0xeb, 0xd6, 0x7a, 0x35, 0x47, 0x7d, 0x22, 0x85, 0x5e, 0x5a, 0xb7, 0x0c, 0x85,
	0x5e, 0x12, 0x0b, 0xee, 0xd0, 0x0b, 0x96, 0xd1, 0x80, 0x59, 0x75, 0xa4, 0xe6, 0x47, 0xb2, 0x01,
	0x8b, 0x31, 0xf3, 0x43, 0x9a, 0x58, 0xb7, 0xf1, 0xc2, 0x9c, 0xec, 0xbf, 0xd6, 0xe0, 0xce, 0x01,
	0x4f, 0x24, 0xf5, 0x24, 0xd9, 0x82, 0xe6, 0xe9, 0x30, 0x8a, 0xdc, 0x84, 0xc6, 0x0c, 0x71, 0x9a,
	0x4e, 0x43, 0x11, 0xbe, 0xa2, 0x31, 0x23, 0xeb, 0xb0, 0x20, 0x43, 0x19, 0x31, 0x84, 0x6b, 0x3a,
	0xfa, 0xa0, 0xa8, 0x2c, 0xa6, 0x61, 0x84, 0x70, 0x4d, 0x47, 0x1f, 0xc8, 0x8f, 0x60, 0x29, 0x3d,
	0xe3, 0x09, 0x73, 0x93, 0x61, 0x7c, 0xc2, 0x32, 0x84, 0x6c, 0x3a, 0x2d, 0xa4, 0x7d, 0x85, 0x24,
	0xa5, 0x69, 0xc6, 0x02, 0xe5, 0x2c, 0x6b, 0xa1, 0x5b, 0xef, 0x35, 0x9d, 0xfc, 0x68, 0xff, 0x65,
	0x19, 0x16, 0x5e, 0x64, 0x34, 0xf1, 0x09, 0x81, 0xdb, 0x05, 0x55, 0xf0, 0x5b, 0x89, 0xf6, 0x43,
	0x91, 0x46, 0xf4, 0x4a, 0xab, 0xa9, 0xb5, 0x69, 0x19, 0x1a, 0x6a, 0xfa, 0x31, 0xb4, 0x4f, 0x79,
	0x16, 0x53, 0x29, 0x99, 0xef, 0x52, 0xdf, 0xcf, 0x98, 0x10, 0x46, 0xbf, 0xd5, 0xd1, 0xc5, 0x73,
	0x4d, 0x1f, 0x1b, 0x70, 0xbb, 0x68, 0xc0, 0x8f, 0x61, 0x35, 0x63, 0x34, 0x52, 0xf1, 0x90, 0xcc,
	0xd5, 0x0c, 0x0b, 0xc8, 0xb0, 0x32, 0xa6, 0x1f, 0x56, 0xda, 0xba, 0x38, 0x6d, 0xeb, 0xcf, 0xa0,
	0xe1, 0x69, 0x17, 0x0b, 0xeb, 0x4e, 0xb7, 0xde, 0x6b, 0x3d, 0xed, 0xf4, 0xa7, 0x72, 0xa9, 0x6f,
	0xa2, 0xe0, 0x8c, 0x78, 0x95, 0x6e, 0x09, 0x0d, 0x3d, 0x61, 0x35, 0xb4, 0x6e, 0x78, 0x20, 0x0f,
	0xa1, 0x95, 0x72, 0x21, 0x69, 0xe4, 0x7a, 0xdc, 0x67, 0x56, 0x13, 0xef, 0x40, 0x93, 0x0e, 0xb8,
	0xcf, 0x08, 0x87, 0xcd, 0x53, 0x9d, 0x38, 0xae, 0x60, 0xd2, 0x1d, 0x7d, 0xab, 0x2c, 0xb2, 0x00,
	0xf1, 0x7f, 0x52, 0x81, 0x8f, 0x3e, 0xef, 0xe7, 0x29, 0xc7, 0x64, 0x31, 0xf9, 0x0e, 0x13, 0x99,
	0x5d, 0x39, 0x1b, 0xa7, 0x95, 0x97, 0xe4, 0xf7, 0x40, 0x74, 0xf0, 0xdc, 0x34, 0x63, 0xa7, 0x2c,
	0x63, 0x89, 0xc7, 0x84, 0xd5, 0x42, 0xa4, 0xc1, 0x4c, 0x24, 0x07, 0x9f, 0x7c, 0x3d, 0x7e, 0xa1,
	0x41, 0xda, 0xd9, 0x24, 0x5d, 0xe5, 0x81, 0xa4, 0x81, 0xb0, 0x96, 0x30, 0x51, 0xf0, 0x5b, 0xe5,
	0x0f, 0xbb, 0xf4, 0xa2, 0xa1, 0xcf, 0xac, 0xe5, 0x6e, 0xad, 0xd7, 0x70, 0xf2, 0x23, 0x79, 0x06,
	0x2d, 0x2f, 0x63, 0x2a, 0x6e, 0xaa, 0xa2, 0xac, 0x0f, 0xba, 0x35, 0x74, 0xb8, 0x2e, 0xb7, 0x7e,
	0x5e, 0x6e, 0xfd, 0xe3, 0xbc, 0xdc, 0x1c, 0xd0, 0xec, 0x8a, 0xa0, 0x1e, 0x0f, 0x53, 0x7f, 0xf4,
	0x78, 0xe5, 0xfa, 0xc7, 0x9a, 0x1d, 0x1f, 0x3f, 0x82, 0x15, 0xc9, 0x55, 0x60, 0x22, 0xee, 0xe9,
	0x46, 0x60, 0xad, 0x76, 0x6b, 0xbd, 0xba, 0xf3, 0x01, 0x92, 0xbf, 0xcc, 0xa9, 0xa4, 0x0f, 0x6b,
	0x98, 0x41, 0xc2, 0xe5, 0xa7, 0x2e, 0xbb, 0x4c, 0x69, 0x22, 0x42, 0x9e, 0x58, 0x6d, 0xb4, 0xaf,
	0xad, 0xaf, 0xde, 0x9c, 0x1e, 0xe6, 0x17, 0x65, 0x7e, 0x9e, 0xb2, 0x0c, 0xe5, 0x58, 0xa4, 0xcc,
	0xff, 0x26, 0xbf, 0x50, 0xce, 0xf9, 0x03, 0x3b, 0x11, 0xa1, 0x64, 0xd6, 0x1a, 0xa6, 0x47, 0x7e,
	0xc4, 0xe4, 0xa1, 0x19, 0x4b, 0xa4, 0xae, 0x9e, 0x75, 0x93, 0x3c, 0x48, 0xc2, 0xe2, 0x19, 0xc0,
	0x9a, 0x0e, 0x62, 0xc6, 0x7c, 0xd7, 0xe3, 0x92, 0x25, 0x34, 0x91, 0xc2, 0xba, 0x8b, 0x50, 0x64,
	0x74, 0x75, 0x90, 0xdf, 0x28, 0xdd, 0xc6, 0x0f, 0x32, 0x4e, 0x7d, 0x57, 0x5e, 0xa5, 0xcc, 0xda,
	0xe8, 0xd6, 0x7b, 0x75, 0xa7, 0x3d, 0xba, 0x72, 0x38, 0xf5, 0x8f, 0xaf, 0x52, 0x46, 0xf6, 0x61,
	0x33, 0x77, 0x0f, 0x72, 0x0a, 0xd7, 0xe3, 0x89, 0x08, 0x7d, 0x96, 0x31, 0xdf, 0xba, 0x87, 0x30,
	0xf7, 0x72, 0x06, 0xf5, 0x40, 0x1c, 0x8c, 0xae, 0x95, 0x5d, 0x69, 0x16, 0x7a, 0x61, 0x12, 0x58,
	0x96, 0xb6, 0xcb, 0x1c, 0xc9, 0x03, 0x00, 0x2a, 0x65, 0x16, 0x9e, 0x0c, 0x25, 0x13, 0xd6, 0x26,
	0x8a, 0x29, 0x50, 0x48, 0x17, 0x5a, 0x3e, 0x13, 0x5e, 0x16, 0xa6, 0xe8, 0xb9, 0x8e, 0xe9, 0x1a,
	0x63, 0x12, 0x79, 0x06, 0x9b, 0x09, 0x0b, 0x83, 0xb3, 0x13, 0x9e, 0x9d, 0x71, 0xae, 0x6c, 0xcf,
	0x32, 0x16, 0x99, 0x30, 0x6e, 0xa1, 0x40, 0xab, 0xc8, 0x70, 0x50, 0xb8, 0x57, 0xfd, 0x22, 0x0e,
	0x93, 0x30, 0x1e, 0xc6, 0xae, 0x1f, 0x0a, 0x49, 0x13, 0x8f, 0x59, 0xdb, 0x18, 0xfa, 0x15, 0x43,
	0x7f, 0x69, 0xc8, 0xe4, 0x3e, 0xc0, 0x89, 0xca, 0x7f, 0x57, 0x84, 0xdf, 0x30, 0xeb, 0x3e, 0x2a,
	0xd2, 0x44, 0xca, 0x51, 0xf8, 0x0d, 0x5e, 0x87, 0x89, 0xc7, 0x63, 0xe6, 0x86, 0xef, 0x32, 0xeb,
	0x81, 0xbe, 0xd6, 0x94, 0x2f, 0xde, 0x65, 0x64, 0x07, 0x96, 0x4d, 0x7b, 0x70, 0x3d, 0x3e, 0x4c,
	0xa4, 0xf5, 0x10, 0x39, 0x96, 0x0c, 0xf1, 0x40, 0xd1, 0x3a, 0x6f, 0x61, 0x6b, 0x4e, 0x19, 0xab,
	0xb1, 0x71, 0xce, 0xae, 0x4c, 0x57, 0x55, 0x9f, 0xe4, 0xa7, 0xb0, 0x70, 0x41, 0xa3, 0xa1, 0xee,
	0xa6, 0xad, 0xa7, 0x0f, 0x2b, 0x6a, 0xb6, 0x28, 0xc6, 0xd1, 0xdc, 0xfb, 0xb7, 0x7e, 0x5e, 0xeb,
	0x9c, 0x43, 0xab, 0x58, 0xaa, 0x3b, 0xb0, 0x3c, 0xce, 0x86, 0x20, 0xa2, 0x06, 0x65, 0x69, 0x44,
	0x7c, 0x15, 0x51, 0x35, 0x8b, 0xc2, 0x24, 0x0a, 0x13, 0x66, 0x46, 0x97, 0x39, 0xa9, 0xe4, 0x54,
	0x4e, 0xf2, 0x5d, 0x1a, 0xf1, 0x24, 0x9f, 0x60, 0x80, 0xa4, 0xe7, 0x8a, 0xd2, 0x79, 0x0b, 0x1b,
	0xd5, 0x5d, 0xa3, 0xc2, 0xa6, 0xfd, 0xb2, 0x4d, 0x1f, 0xce, 0xec, 0x43, 0x05, 0x59, 0x05, 0xc3,
	0xec, 0x7f, 0xd5, 0xa0, 0x7e, 0x4c, 0x83, 0xf7, 0x1d, 0x42, 0x85, 0xfe, 0x54, 0x2f, 0xf7, 0x27,
	0x55, 0x30, 0xd1, 0x30, 0xa3, 0x91, 0x5b, 0x92, 0xa1, 0xe7, 0x4f, 0x5b, 0x5f, 0xbd, 0x2c, 0x48,
	0x9a, 0x28, 0x59, 0x3d, 0x2d, 0x0b, 0x25, 0x6b, 0x7f, 0x04, 0x2b, 0xaf, 0x98, 0x44, 0x63, 0x1c,
	0xf6, 0x6e, 0xc8, 0x84, 0xac, 0x52, 0xda, 0x7e, 0x0c, 0xf7, 0x72, 0x36, 0x13, 0x4c, 0x31, 0x8f,
	0xfd, 0x33, 0xd8, 0xca, 0xd9, 0xc5, 0xeb, 0x30, 0xc9, 0xf3, 0x37, 0x7f, 0x82, 0xb3, 0x29, 0x66,
	0xc2, 0xaa, 0xa1, 0x3e, 0xfa, 0x50, 0xc4, 0x30, 0xe3, 0x6c, 0x2e, 0xc6, 0x27, 0xb0, 0x3e, 0xc2,
	0x78, 0x31, 0x8c, 0xce, 0xe7, 0x0b, 0xff, 0xf7, 0x2d, 0x58, 0x3b, 0x62, 0x34, 0xf3, 0xce, 0xf4,
	0x8b, 0x9c, 0x7b, 0x32, 0x1a, 0xb5, 0xe9, 0x68, 0xe4, 0x13, 0xe4, 0x56, 0x61, 0x82, 0x4c, 0xa5,
	0x6a, 0xbd, 0x5b, 0xef, 0x2d, 0x4c, 0xa4, 0xea, 0x0e, 0x2c, 0x63, 0xa3, 0xf3, 0xae, 0x70, 0xb6,
	0x09, 0xeb, 0x36, 0x4a, 0x58, 0x32, 0x44, 0x95, 0x3b, 0x82, 0x7c, 0x0a, 0xeb, 0x66, 0x79, 0x29,
	0xf7, 0x73, 0x1d, 0x2a, 0x33, 0x1b, 0x4b, 0x0d, 0xbd, 0xfc, 0x62, 0xdc, 0xd1, 0x17, 0x27, 0x5e,
	0x8c, 0x5b, 0x7a, 0xb9, 0xc1, 0xdd, 0x99, 0x6a, 0x70, 0xe5, 0xbe, 0xd1, 0x98, 0xe8, 0x1b, 0xf6,
	0x1b, 0x68, 0x7f, 0x19, 0x0a, 0x59, 0x76, 0xdc, 0x16, 0x34, 0x53, 0x1a, 0x30, 0xdd, 0x89, 0x94,
	0xd7, 0x16, 0x9c, 0x86, 0x22, 0xe4, 0x8d, 0x08, 0x2f, 0x25, 0x3f, 0x67, 0x89, 0xc9, 0x70, 0x64,
	0x3f, 0x56, 0x04, 0x3b, 0x01, 0x52, 0x14, 0x28, 0x52, 0x9e, 0x08, 0x46, 0x3e, 0x85, 0x45, 0x6c,
	0x65, 0x3a, 0x72, 0xad, 0xa7, 0xd6, 0xac, 0xaa, 0x73, 0x0c, 0x1f, 0xd9, 0x85, 0x95, 0x84, 0x5d,
	0x4a, 0x77, 0x0a, 0x6b, 0x59, 0x91, 0xbf, 0x1e, 0xe1, 0x3d, 0x87, 0x95, 0xa3, 0x89, 0x24, 0xef,
	0xc3, 0x02, 0x0a, 0x41, 0xd5, 0xe7, 0x61, 0x69, 0x36, 0xbb, 0x07, 0xe4, 0x25, 0x8b, 0x98, 0x64,
	0xd7, 0x96, 0xca, 0x0e, 0x2c, 0xbf, 0x62, 0xf2, 0x98, 0x06, 0xf3, 0x98, 0x3e, 0x87, 0xe5, 0xa3,
	0x12, 0x53, 0x0f, 0xea, 0x92, 0x06, 0x46, 0x9b, 0x8d, 0x0a, 0x6d, 0x14, 0xaf, 0x62, 0xb1, 0x5f,
	0xc3, 0x8a, 0x72, 0xde, 0x31, 0x0d, 0x7e, 0x90, 0x58, 0x9c, 0xc2, 0xea, 0x58, 0x9c, 0x89, 0xc4,
	0x9e, 0xc9, 0x78, 0x1d, 0x87, 0x59, 0xda, 0xe8, 0x4a, 0xb8, 0x69, 0x0c, 0x76, 0x61, 0x55, 0x3b,
	0xf0, 0x1a, 0xcf, 0xfc, 0xa7, 0x06, 0xd6, 0x74, 0xab, 0x31, 0x8a, 0xfd, 0x1a, 0x1a, 0x66, 0x8d,
	0xcc, 0x95, 0xfb, 0xbc, 0x42, 0xb9, 0x59, 0xcf, 0xf3, 0x39, 0x64, 0x96, 0xc5, 0x91, 0xa8, 0xce,
	0x6f, 0x61, 0xb9, 0x74, 0xf5, 0x83, 0x4e, 0x39, 0xdb, 0x19, 0x1b, 0x34, 0xee, 0x6b, 0xc6, 0xa0,
	0xe2, 0x76, 0x5f, 0xbb, 0xf9, 0x76, 0x6f, 0xff, 0xaf, 0x06, 0xdb, 0xd5, 0x1d, 0xd6, 0x08, 0xce,
	0xa0, 0x3d, 0xb9, 0x54, 0xe4, 0x08, 0x87, 0x73, 0x5c, 0x56, 0x25, 0xab, 0xff, 0xba, 0xbc, 0x85,
	0x18, 0xf7, 0xad, 0x4e, 0x2c, 0x27, 0xa2, 0x73, 0x00, 0x77, 0x2b, 0x59, 0x2b, 0xdc, 0xb9, 0x5e,
	0x74, 0x67, 0xbd, 0xe8, 0xad, 0x2f, 0xe0, 0xee, 0x44, 0x5b, 0x7f, 0xdf, 0xf6, 0x60, 0xff, 0x0a,
	0xd6, 0xcb, 0x2d, 0xff, 0x7d, 0x25, 0x3d, 0xfd, 0xe7, 0x12, 0x34, 0xde, 0x98, 0x5b, 0xc2, 0xa0,
	0x91, 0x6b, 0x48, 0xec, 0x39, 0xbe, 0x34, 0x59, 0xde, 0x99, 0x29, 0xde, 0xde, 0xfa, 0xf3, 0x7f,
	0xff, 0xff, 0xf7, 0x5b, 0x77, 0xc9, 0xda, 0xe0, 0xe2, 0xc9, 0xe0, 0x8f, 0x2a, 0xfd, 0x7f, 0xa1,
	0x01, 0x07, 0x7b, 0xdf, 0x92, 0xbf, 0xd5, 0x60, 0x75, 0x32, 0x93, 0xc9, 0xde, 0x8d, 0xd2, 0x5d,
	0xe3, 0x7e, 0xfc, 0x3d, 0x4a, 0xc3, 0xfe, 0x10, 0x55, 0x79, 0x40, 0xb6, 0x95, 0x2a, 0x79, 0x61,
	0xcc, 0xd5, 0x29, 0xcf, 0xe5, 0xb9, 0x3a, 0x4d, 0x0c, 0xf2, 0xb9, 0x3a, 0x4d, 0x16, 0x47, 0x59,
	0xa7, 0x3c, 0xf5, 0xa7, 0x74, 0xfa, 0x47, 0xad, 0xb0, 0x08, 0x14, 0xd2, 0x97, 0xf4, 0x6f, 0x9c,
	0xe7, 0x5a, 0xb7, 0xc1, 0xf7, 0xac, 0x0b, 0x7b, 0x17, 0xf5, 0xeb, 0xda, 0x5b, 0x4a, 0x3f, 0xa3,
	0x90, 0x29, 0x8a, 0xc7, 0x79, 0xd1, 0xed, 0xd7, 0xf6, 0xc8, 0x9f, 0x70, 0x22, 0x8c, 0x53, 0x9a,
	0x3c, 0x9a, 0x87, 0x54, 0xd8, 0x65, 0x3a, 0xbd, 0xeb, 0x19, 0x8d, 0x2e, 0x1d, 0xd4, 0x65, 0xdd,
	0x5e, 0x29, 0xe8, 0x72, 0x32, 0x8c, 0xce, 0x15, 0x7e, 0x0c, 0x30, 0x1e, 0xb7, 0xa4, 0x6a, 0x99,
	0x9d, 0x1a, 0xef, 0x9d, 0x8f, 0xae, 0xe1, 0x32, 0xb0, 0x04, 0x61, 0x97, 0x08, 0x8c, 0x61, 0xc9,
	0xb7, 0xb0, 0x54, 0x2c, 0x3b, 0xb2, 0x5b, 0x21, 0xaa, 0x62, 0x15, 0xeb, 0x3c, 0xba, 0x96, 0xcf,
	0x80, 0x6e, 0x23, 0xe8, 0x86, 0xdd, 0x2e, 0xd8, 0x2a, 0x90, 0x51, 0x59, 0x7b, 0x01, 0x8d, 0xa3,
	0x79, 0xe5, 0x79, 0x74, 0xe3, 0xf2, 0xfc, 0x04, 0x71, 0x76, 0xed, 0xfb, 0x58, 0x9e, 0x08, 0xd4,
	0x2f, 0x27, 0xdf, 0xbe, 0x60, 0x72, 0x5f, 0x6f, 0x08, 0x24, 0x84, 0x56, 0x61, 0x43, 0x20, 0x55,
	0x0e, 0x9c, 0xde, 0x20, 0x3a, 0x1b, 0x53, 0xbf, 0x07, 0x0e, 0xe3, 0x54, 0x5e, 0xe5, 0xad, 0x61,
	0xaf, 0xb2, 0x35, 0xfc, 0x0e, 0x16, 0xf5, 0x8a, 0x41, 0xba, 0xd5, 0x09, 0x32, 0x9e, 0xb1, 0x9d,
	0x19, 0xd3, 0xdb, 0xde, 0x44, 0x80, 0x35, 0xd2, 0x1e, 0x03, 0xa8, 0x79, 0xae, 0xc4, 0x33, 0x68,
	0xe4, 0x2b, 0x41, 0xa5, 0x07, 0x27, 0xd6, 0x8f, 0xce, 0xce, 0x5c, 0x1e, 0x13, 0xb4, 0x55, 0xc4,
	0x03, 0xd2, 0x50, 0x78, 0xb8, 0x39, 0xbc, 0x85, 0xc5, 0xa3, 0xd9, 0x56, 0x1c, 0xdd, 0xc8, 0x8a,
	0xbc, 0x04, 0x37, 0xd1, 0x0a, 0x49, 0x83, 0x7e, 0xd1, 0x12, 0x0c, 0x8f, 0x5a, 0x9a, 0x88, 0x07,
	0xcd, 0xd1, 0xf6, 0x41, 0x76, 0x66, 0x86, 0xa6, 0x84, 0x58, 0x1d, 0x18, 0xe3, 0xb7, 0xbd, 0x69,
	0xbf, 0xbd, 0x78, 0xf5, 0x9b, 0xc3, 0x20, 0x94, 0x67, 0xc3, 0x93, 0xbe, 0xc7, 0xe3, 0x01, 0x62,
	0x3c, 0xa6, 0x61, 0xfe, 0x91, 0x86, 0x62, 0x10, 0xb0, 0x04, 0xc5, 0x0d, 0x02, 0x3e, 0x98, 0xfa,
	0x65, 0xfc, 0x2c, 0xff, 0x3e, 0x59, 0x44, 0xa6, 0xcf, 0xbe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x1e, 0x9c, 0xa9, 0x57, 0x16, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OntologyClient is the client API for Ontology service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OntologyClient interface {
	// Gets a brand.
	GetBrand(ctx context.Context, in *GetBrandRequest, opts ...grpc.CallOption) (*Brand, error)
	// Gets features for a brand.
	GetBrandFeatures(ctx context.Context, in *GetBrandFeaturesRequest, opts ...grpc.CallOption) (*GetBrandFeaturesResponse, error)
	// Gets features for a brand.
	GetBrandContacts(ctx context.Context, in *GetBrandContactsRequest, opts ...grpc.CallOption) (*GetBrandContactsResponse, error)
	// Gets min distanct for a number brand.
	GetBrandsMinDistance(ctx context.Context, in *GetBrandsMinDistanceRequest, opts ...grpc.CallOption) (*GetBrandsMinDistanceResponse, error)
	// Gets a number of brands.
	GetBrandsBulk(ctx context.Context, in *GetBrandsBulkRequest, opts ...grpc.CallOption) (*GetBrandsBulkResponse, error)
	// Lists brands.
	ListBrands(ctx context.Context, in *ListBrandsRequest, opts ...grpc.CallOption) (*ListBrandsResponse, error)
	// Searches brands.
	SearchBrands(ctx context.Context, in *SearchBrandsRequest, opts ...grpc.CallOption) (*SearchBrandsResponse, error)
	// Sets a brand.
	SetBrand(ctx context.Context, in *SetBrandRequest, opts ...grpc.CallOption) (*Brand, error)
	// Deletes a brand.
	DeleteBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Gets a tag.
	GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error)
	// Lists tags.
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// Sets a tag.
	SetTag(ctx context.Context, in *SetTagRequest, opts ...grpc.CallOption) (*Tag, error)
	// Deletes a tag.
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type ontologyClient struct {
	cc *grpc.ClientConn
}

func NewOntologyClient(cc *grpc.ClientConn) OntologyClient {
	return &ontologyClient{cc}
}

func (c *ontologyClient) GetBrand(ctx context.Context, in *GetBrandRequest, opts ...grpc.CallOption) (*Brand, error) {
	out := new(Brand)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/GetBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) GetBrandFeatures(ctx context.Context, in *GetBrandFeaturesRequest, opts ...grpc.CallOption) (*GetBrandFeaturesResponse, error) {
	out := new(GetBrandFeaturesResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/GetBrandFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) GetBrandContacts(ctx context.Context, in *GetBrandContactsRequest, opts ...grpc.CallOption) (*GetBrandContactsResponse, error) {
	out := new(GetBrandContactsResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/GetBrandContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) GetBrandsMinDistance(ctx context.Context, in *GetBrandsMinDistanceRequest, opts ...grpc.CallOption) (*GetBrandsMinDistanceResponse, error) {
	out := new(GetBrandsMinDistanceResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/GetBrandsMinDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) GetBrandsBulk(ctx context.Context, in *GetBrandsBulkRequest, opts ...grpc.CallOption) (*GetBrandsBulkResponse, error) {
	out := new(GetBrandsBulkResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/GetBrandsBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) ListBrands(ctx context.Context, in *ListBrandsRequest, opts ...grpc.CallOption) (*ListBrandsResponse, error) {
	out := new(ListBrandsResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/ListBrands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) SearchBrands(ctx context.Context, in *SearchBrandsRequest, opts ...grpc.CallOption) (*SearchBrandsResponse, error) {
	out := new(SearchBrandsResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/SearchBrands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) SetBrand(ctx context.Context, in *SetBrandRequest, opts ...grpc.CallOption) (*Brand, error) {
	out := new(Brand)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/SetBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) DeleteBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/DeleteBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	out := new(Tag)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/GetTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/ListTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) SetTag(ctx context.Context, in *SetTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	out := new(Tag)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/SetTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/topos.ontology.v1.Ontology/DeleteTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OntologyServer is the server API for Ontology service.
type OntologyServer interface {
	// Gets a brand.
	GetBrand(context.Context, *GetBrandRequest) (*Brand, error)
	// Gets features for a brand.
	GetBrandFeatures(context.Context, *GetBrandFeaturesRequest) (*GetBrandFeaturesResponse, error)
	// Gets features for a brand.
	GetBrandContacts(context.Context, *GetBrandContactsRequest) (*GetBrandContactsResponse, error)
	// Gets min distanct for a number brand.
	GetBrandsMinDistance(context.Context, *GetBrandsMinDistanceRequest) (*GetBrandsMinDistanceResponse, error)
	// Gets a number of brands.
	GetBrandsBulk(context.Context, *GetBrandsBulkRequest) (*GetBrandsBulkResponse, error)
	// Lists brands.
	ListBrands(context.Context, *ListBrandsRequest) (*ListBrandsResponse, error)
	// Searches brands.
	SearchBrands(context.Context, *SearchBrandsRequest) (*SearchBrandsResponse, error)
	// Sets a brand.
	SetBrand(context.Context, *SetBrandRequest) (*Brand, error)
	// Deletes a brand.
	DeleteBrand(context.Context, *DeleteBrandRequest) (*empty.Empty, error)
	// Gets a tag.
	GetTag(context.Context, *GetTagRequest) (*Tag, error)
	// Lists tags.
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// Sets a tag.
	SetTag(context.Context, *SetTagRequest) (*Tag, error)
	// Deletes a tag.
	DeleteTag(context.Context, *DeleteTagRequest) (*empty.Empty, error)
}

// UnimplementedOntologyServer can be embedded to have forward compatible implementations.
type UnimplementedOntologyServer struct {
}

func (*UnimplementedOntologyServer) GetBrand(ctx context.Context, req *GetBrandRequest) (*Brand, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrand not implemented")
}
func (*UnimplementedOntologyServer) GetBrandFeatures(ctx context.Context, req *GetBrandFeaturesRequest) (*GetBrandFeaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandFeatures not implemented")
}
func (*UnimplementedOntologyServer) GetBrandContacts(ctx context.Context, req *GetBrandContactsRequest) (*GetBrandContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandContacts not implemented")
}
func (*UnimplementedOntologyServer) GetBrandsMinDistance(ctx context.Context, req *GetBrandsMinDistanceRequest) (*GetBrandsMinDistanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandsMinDistance not implemented")
}
func (*UnimplementedOntologyServer) GetBrandsBulk(ctx context.Context, req *GetBrandsBulkRequest) (*GetBrandsBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandsBulk not implemented")
}
func (*UnimplementedOntologyServer) ListBrands(ctx context.Context, req *ListBrandsRequest) (*ListBrandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBrands not implemented")
}
func (*UnimplementedOntologyServer) SearchBrands(ctx context.Context, req *SearchBrandsRequest) (*SearchBrandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBrands not implemented")
}
func (*UnimplementedOntologyServer) SetBrand(ctx context.Context, req *SetBrandRequest) (*Brand, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBrand not implemented")
}
func (*UnimplementedOntologyServer) DeleteBrand(ctx context.Context, req *DeleteBrandRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBrand not implemented")
}
func (*UnimplementedOntologyServer) GetTag(ctx context.Context, req *GetTagRequest) (*Tag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTag not implemented")
}
func (*UnimplementedOntologyServer) ListTags(ctx context.Context, req *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTags not implemented")
}
func (*UnimplementedOntologyServer) SetTag(ctx context.Context, req *SetTagRequest) (*Tag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTag not implemented")
}
func (*UnimplementedOntologyServer) DeleteTag(ctx context.Context, req *DeleteTagRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTag not implemented")
}

func RegisterOntologyServer(s *grpc.Server, srv OntologyServer) {
	s.RegisterService(&_Ontology_serviceDesc, srv)
}

func _Ontology_GetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).GetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/GetBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).GetBrand(ctx, req.(*GetBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_GetBrandFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).GetBrandFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/GetBrandFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).GetBrandFeatures(ctx, req.(*GetBrandFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_GetBrandContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).GetBrandContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/GetBrandContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).GetBrandContacts(ctx, req.(*GetBrandContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_GetBrandsMinDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandsMinDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).GetBrandsMinDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/GetBrandsMinDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).GetBrandsMinDistance(ctx, req.(*GetBrandsMinDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_GetBrandsBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandsBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).GetBrandsBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/GetBrandsBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).GetBrandsBulk(ctx, req.(*GetBrandsBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_ListBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBrandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).ListBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/ListBrands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).ListBrands(ctx, req.(*ListBrandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_SearchBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBrandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).SearchBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/SearchBrands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).SearchBrands(ctx, req.(*SearchBrandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_SetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).SetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/SetBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).SetBrand(ctx, req.(*SetBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_DeleteBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).DeleteBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/DeleteBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).DeleteBrand(ctx, req.(*DeleteBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/GetTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).GetTag(ctx, req.(*GetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/ListTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_SetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).SetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/SetTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).SetTag(ctx, req.(*SetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topos.ontology.v1.Ontology/DeleteTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ontology_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topos.ontology.v1.Ontology",
	HandlerType: (*OntologyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBrand",
			Handler:    _Ontology_GetBrand_Handler,
		},
		{
			MethodName: "GetBrandFeatures",
			Handler:    _Ontology_GetBrandFeatures_Handler,
		},
		{
			MethodName: "GetBrandContacts",
			Handler:    _Ontology_GetBrandContacts_Handler,
		},
		{
			MethodName: "GetBrandsMinDistance",
			Handler:    _Ontology_GetBrandsMinDistance_Handler,
		},
		{
			MethodName: "GetBrandsBulk",
			Handler:    _Ontology_GetBrandsBulk_Handler,
		},
		{
			MethodName: "ListBrands",
			Handler:    _Ontology_ListBrands_Handler,
		},
		{
			MethodName: "SearchBrands",
			Handler:    _Ontology_SearchBrands_Handler,
		},
		{
			MethodName: "SetBrand",
			Handler:    _Ontology_SetBrand_Handler,
		},
		{
			MethodName: "DeleteBrand",
			Handler:    _Ontology_DeleteBrand_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _Ontology_GetTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Ontology_ListTags_Handler,
		},
		{
			MethodName: "SetTag",
			Handler:    _Ontology_SetTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Ontology_DeleteTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topos/ontology/v1/ontology.proto",
}
