type: google.api.Service
config_version: 3
name: v1.ontology.endpoints.topos.com

title: Topos Ontology API
apis:
 - name: topos.ontology.v1.Ontology

authentication:
  providers:
  - id: auth0_jwk
    issuer: https://auth.topos.com/
    jwks_uri: https://auth.topos.com/.well-known/jwks.json
    audiences:
    - endpoints.topos.com
    - https://endpoints.topos.com
  rules:
  - selector: "*"
    requirements:
      - provider_id: auth0_jwk

usage:
  rules:
    - selector: "topos.ontology.v1.*"
      allow_unregistered_calls: true
